# Don't change this! Version used to track needed updates.
version = 0
biomeColorRain = true
biomeParticlesRadius = 32
mushroomSporeBiomes = [
    "minecraft:mushroom_fields"
]
mushroomSporeDensity = 6
fireflyBiomes = [
    "minecraft:swamp",
    "minecraft:mangrove_swamp"
]
fireflyDensity = 0
pollenBiomes = [
    "minecraft:flower_forest",
    "minecraft:sunflower_plains"
]
pollenDensity = 3
sculkDustBiomes = [
    "minecraft:deep_dark"
]
sculkDustDensity = 5