# Don't change this! Version used to track needed updates.
version = 0
axeStripParticles = true
axeScrapeParticlesDisplayType = "DEFAULT"
axeWaxOffParticlesDisplayType = "DEFAULT"
boneMealUsingParticles = true
flintAndSteelParticles = true
increasedItemBreakParticles = true
waterEvaporateFromBucketSteam = true
fluidBucketUseParticles = true
powderSnowBucketUseParticles = true
powderSnowBucketBlockPlaceSound = true
lingeringPotionClouds = true
splashPotionClouds = true
structureVoidItemMarker = true
spawnEggUseSoundVolume = 0.5
spawnEggUseParticles = false

[itemRarity]
particlesDisplayType = "ON"
particleColorType = "RARITY_COLOR"
mixedColorName = false
useItemBorder = false
colorOverrides = [  ]
particleMaxHeight = 0.8464052
particleMaxSpeed = 0.7457516
particleDensity = 0.5970588235294116

[projectiles]
enderPearlTrailDensity = 0.5
xpBottleParticlesDisplayType = "DEFAULT"
xpBottleParticlesDensity = 10
eggSmashSoundVolume = 0.5
eggSplatParticles = true
snowballTrailDensity = 0.5
snowballPoofsHaveSnowflakes = true
snowballPoofSoundVolume = 0.3