KeyBindEvents.modify(event => {

	/**
	 * @type {$KeyMapping$$Type}
	 */
	const removedKeybinds = [
		"artifacts.key.helium_flamingo.activate",
		"artifacts.key.night_vision_goggles.toggle",
		"artifacts.key.universal_attractor.toggle",
		"create.keyinfo.rotate_menu",
		"gnetum.config.keyMapping",
		"key.disable_voice_chat",
		"key.entityculling.toggle",
		"key.exposure.camera_controls",
		"key.ftbteams.open_gui",
		"key.hammerlib.render_item",
		"key.hide_icons",
		"key.invtweaks_sort_either.desc",
		"key.invtweaks_sort_inventory.desc",
		"key.invtweaks_sort_player.desc",
		"key.aether.open_accessories.desc",
		"key.ars_additions.open_lectern",
		// "key.ars_nouveau.familiar_toggle",
		// "key.ars_nouveau.qc1",
		// "key.ars_nouveau.qc10",
		// "key.ars_nouveau.qc2",
		// "key.ars_nouveau.qc3",
		// "key.ars_nouveau.qc4",
		// "key.ars_nouveau.qc5",
		// "key.ars_nouveau.qc6",
		// "key.ars_nouveau.qc7",
		// "key.ars_nouveau.qc8",
		// "key.ars_nouveau.qc9",
		"key.craftingtweaks.balance",
		"key.craftingtweaks.clear",
		"key.craftingtweaks.decompress_all",
		"key.craftingtweaks.decompress_one",
		"key.craftingtweaks.decompress_stack",
		"key.craftingtweaks.force_clear",
		"key.craftingtweaks.rotate",
		"key.craftingtweaks.rotate_counter_clockwise",
		"key.craftingtweaks.spread",
		"key.craftingtweaks.transfer_stack",
		"key.immersiveoverlays.settings",
		"key.immersiveoverlays.toggle",
		"key.mobhealthbar.chooser",
		"key.modmenu.open_menu",
		"key.pingwheel.open_settings",
		// "key.push_to_talk",
		"key.quickskin.open_menu",
		"key.shouldersurfing.enter_first_person",
		"key.shouldersurfing.enter_shoulder_surfing",
		"key.shouldersurfing.enter_third_person_back",
		"key.shouldersurfing.enter_third_person_front",
		// "key.showmeyourskin.open_settings",
		// "key.smoothCamera",
		"key.socialInteractions",
		"key.swapOffhand",
		"key.toggleCarriedItemTooltips",
		"key.toggleSelectedItemTooltips",
		"key.toggleVisualItemContents",
		"key.travelersbackpack.ability",
		"key.travelersbackpack.sort",
		"key.travelersbackpack.toggle_upgrade_0",
		"key.travelersbackpack.toggle_upgrade_1",
		"key.travelersbackpack.toggle_upgrade_2",
		"key.travelersbackpack.toggle_upgrade_3",
		// "key.voice_chat_settings",
		// "key.whisper",
		// "key.iris.keybind.reload",
		// "key.iris.keybind.shaderPackSelection",
		// "key.iris.keybind.toggleShaders",
		"key.modernfix.config",
		// "key.mount_jump",
		"key.pickup.item",
		"key.shouldersurfing.toggle_camera_coupling",
		"key.shouldersurfing.toggle_first_person",
		"key.shouldersurfing.toggle_third_person_back",
		"key.shouldersurfing.toggle_third_person_front",
		"key.shouldersurfing.toggle_x_offset_presets",
		"key.shouldersurfing.toggle_y_offset_presets",
		"key.shouldersurfing.toggle_z_offset_presets",
		"key.screenshot_viewer.open_screenshots_screen",
		// "key.showmeyourskin.global_toggle",
		"key.spectatorOutlines",
		"key.trade_cycling.cycle_trades",
		"key.toastcontrol.clear",
		"key.veinmining.activate.desc",
		"key.voice_chat_adjust_volumes",
		"key.voice_chat_group",
		"key.voice_chat_toggle_recording",
		"obscure_tooltips_fix.print_screen",
		"ping-wheel.key.open-settings",
		"quark.emote.cheer",
		"quark.emote.clap",
		"quark.emote.facepalm",
		"quark.emote.headbang",
		"quark.emote.no",
		"quark.emote.point",
		"quark.emote.salute",
		"quark.emote.shrug",
		"quark.emote.think",
		"quark.emote.wave",
		"quark.emote.weep",
		"quark.keybind.autorun",
		"quark.keybind.narrator_full_readout",
		"quark.keybind.narrator_readout",
		"quark.keybind.patreon_emote.dab",
		"quark.keybind.patreon_emote.dance",
		"quark.keybind.patreon_emote.exorcist",
		"quark.keybind.patreon_emote.jet",
		"quark.keybind.patreon_emote.tpose",
		"quark.keybind.patreon_emote.zombie",
		"quark.keybind.shift_lock",
		"quark.keybind.sort_container",
		"quark.keybind.sort_player",
		"quark.keybind.transfer_extract",
		"quark.keybind.transfer_insert",
		"terrastorage.keybinding.sort_inventory_bind",
		"treechop.key.cycle_sneak_behavior",
		"treechop.key.open_settings_overlay",
		"treechop.key.toggle_chopping",
		"treechop.key.toggle_felling"
	]

	const allKeybinds = KeyBindUtil.getAllKeyName();
	removedKeybinds.forEach(key => {
		for (let i in allKeybinds) {
			if (allKeybinds[i].toString().includes(key)) {
				event.remove(key);
				event.addHideKey(key);
			}
		}
	})
})

KeyBindEvents.register(event => {
	event.create('adjcore.what_is_this', GLFW.GLFW_KEY_GRAVE_ACCENT, 'key.categories.adjcore')
		.addModifier(KeyModifier.ALT);
})
