const RemovedItems = {
	list: [
		'minecraft:shield',
		'minecraft:enchanting_table',

		'born_in_chaos_v1:mint_ice_cream',

		'tide:depth_meter',
		'tide:pocket_watch',
		'tide:lunar_calendar',
		'tide:climate_gauge',
		'tide:weather_radio',
		'tide:enchanted_pocket_watch',

		'neapolitan:chocolate_block',

		'upgrade_aquatic:thrasher_tooth',

		'aquamirae:divider',
		'aquamirae:poisoned_chakra',
		'aquamirae:maze_rose',
		'aquamirae:terrible_sword',

		'aether:chainmail_gloves',

		'rediscovered:quiver',
		'rediscovered:grass_slab',
		'rediscovered:podzol_slab',
		'rediscovered:mycelium_slab',
		'rediscovered:dirt_path_slab',
		'rediscovered:dirt_slab',
		'rediscovered:coarse_dirt_slab',
		'rediscovered:rooted_dirt_slab',

		/quark:paper_lantern.*/,
		/quark:.*limestone.*/,
		/quark:vertical_.*planks/,

		'create:oak_window_pane',
		'create:spruce_window_pane',
		'create:birch_window_pane',
		'create:jungle_window_pane',
		'create:dark_oak_window_pane',
		'create:acacia_window_pane',
		'create:crimson_window_pane',
		'create:warped_window_pane',
		'create:cherry_window_pane',
		'create:mangrove_window_pane',
		'create:bamboo_window_pane',
		'create:oak_window',
		'create:spruce_window',
		'create:birch_window',
		'create:jungle_window',
		'create:dark_oak_window',
		'create:acacia_window',
		'create:crimson_window',
		'create:warped_window',
		'create:cherry_window',
		'create:mangrove_window',
		'create:bamboo_window',

		'twilightforest:moss_patch',
		'twilightforest:mayapple',
		/twilightforest:charm_of_keeping_.*/,
		'twilightforest:red_thread',
		'twilightforest:crumble_horn',
		/twilightforest:sorting_/,
		'twilightdelight:sorting_cabinet',
		/twilightforest:hollow_.*_log/,
		/umbral_skies:hollow_.*_log/,
		/twilightforest:hollow_.*_stem/,
		/umbral_skies:hollow_.*_stem/,
		/twilightforest:.*_trophy/,
		/umbral_skies:.*_trophy/,
		/twilightforest:.*_skull_candle/,
		'twilightforest:glass_sword',
		'twilightforest:steeleaf_helmet',
		'twilightforest:steeleaf_chestplate',
		'twilightforest:steeleaf_leggings',
		'twilightforest:steeleaf_boots',
		'twilightforest:steeleaf_sword',
		'twilightforest:steeleaf_axe',
		'twilightforest:steeleaf_pickaxe',
		'twilightforest:steeleaf_shovel',
		'twilightforest:steeleaf_hoe',
		'twilightdelight:steeleaf_knife',
		'twilightforest:spiral_bricks',
		'twilightforest:raw_venison',
		'twilightdelight:raw_venison_rib',
		'twilightforest:cooked_venison',
		'twilightdelight:cooked_venison_rib',
		'twilightforest:knightmetal_ring',
		'twilightforest:ironwood_sword',
		'twilightdelight:ironwood_knife',
		'twilightforest:phantom_helmet',
		'twilightforest:phantom_chestplate',
		'twilightforest:phantom_gloves',
		'twilightdelight:knightmetal_knife',
		'twilightforest:knightmetal_pickaxe',
		'twilightforest:block_and_chain',
		'twilightforest:moon_dial',
		/twilightforest:.*nagastone.*_right/,
		'twilightforest:fiery_tears',
		'twilightforest:clover_patch',
		'twilightforest:chopped_clover',

		'handcrafted:wood_plate',
		'handcrafted:wood_cup',
		'handcrafted:wood_cookery_combo',
		'handcrafted:wood_bowl',

		/handcrafted:.*_shelf/,
		/handcrafted:.*_drawer/,
		/handcrafted:.*_trim/,

		/hearth_and_home:.*_parquet/,
		/hearth_and_home:.*_trim/,
		/hearth_and_home:.*_sanded_wood/,
		/hearth_and_home:polished_calcite/,
		/hearth_and_home:polished_obsidian/,
		/hearth_and_home:thatch.*/,

		'v_slab_compat:phantasm/polished_obsidian_bricks_vertical_slab',

		'cataclysm:meat_shredder',
		'cataclysm:ignitium_elytra_chestplate',
		/cataclysm:stone_tile.*/,
		'cataclysm:cursed_bow',
		'cataclysm:wrath_of_the_desert',
		'v_slab_compat:cataclysm/stone_tile_vertical_slab',
		'cataclysm:polished_sandstone',
		'cataclysm:blackstone_pillar',

		'netherexp:shotgun_fist',
		'netherexp:shotgun_core',
		'netherexp:shotgun_barrel',
		'netherexp:pump_charge_upgrade_smithing_template',
		'netherexp:pump_charge_shotgun',
		/netherexp:.*_skull_candle/,
		'jadensnetherexpansiondelight:ecto_knife',
		'jadensnetherexpansiondelight:ecto_ingot',

		'verdantvibes:gardening_table',

		'enligthened_end:dashing_leggings_leggings',

		'experienceobelisk:cognitive_rod',
		'experienceobelisk:cognitive_sword',
		'experienceobelisk:cognitive_helmet',
		'experienceobelisk:cognitive_chestplate',
		'experienceobelisk:cognitive_leggings',
		'experienceobelisk:cognitive_boots',
		'experienceobelisk:cognitive_bow',

		'artifacts:power_glove',
		'artifacts:obsidian_skull',
		'artifacts:fire_gauntlet',
		'artifacts:panic_necklace',
		'artifacts:feral_claws',
		'artifacts:flippers',
		'artifacts:aqua_dashers',
		'artifacts:cloud_in_a_bottle',
		'artifacts:cross_necklace',
		'artifacts:pocket_piston',
		'artifacts:thorn_pendant',

		'spelunkers_charm:crate',
		'spelunkers_charm:encased_geyser',
		'spelunkers_charm:rock',
		'spelunkers_charm:deepslate_rock',
		'spelunkers_charm:dripstone_rock',
		'spelunkers_charm:basalt_rock',
		'spelunkers_charm:redstone_cluster',
		'spelunkers_charm:candle_helmet',

		/witherstormmod:gold_command_block_.*/,
		/witherstormmod:wooden_command_block_.*/,
		/witherstormmod:iron_command_block_.*/,
		/witherstormmod:stone_command_block_.*/,
		'witherstormmod:eye_of_the_storm',
		'witherstorm_delight:flint_command_block_knife',
		'witherstorm_delight:stone_command_block_knife',
		'witherstorm_delight:iron_command_block_knife',
		'witherstorm_delight:gold_command_block_knife',
		'witherstorm_delight:netherite_command_block_knife',

		/mythicmetals:.*silver.*/,

		'mythicmeltas:carmot_ore',
		'mythicmeltas:deepslate_carmot_ore',
		'mythicmetals:carmot_ingot',
		'mythicmetals:raw_carmot',
		'mythicmetals:carmot_nugget',
		'mythicmetals:carmot_helmet',
		'mythicmetals:carmot_chestplate',
		'mythicmetals:carmot_leggings',
		'mythicmetals:carmot_sword',
		'mythicmetals:carmot_axe',
		'mythicmetals:carmot_shovel',
		'mythicmetals:carmot_pickaxe',
		'mythicmetals:carmot_hoe',
		'mythicmetals:carmot_boots',
		'mythicmetals:carmot_block',
		'mythicmetals:carmot_ore',
		'mythicmetals:deepslate_carmot_ore',
		'mythicmetals:raw_carmot_block',
		'mythicmetals:carmot_block',
		'mythicmetals:carmot_staff',
		'mythicmetals:carmot_staff_smithing_template',
		'mythicmetals:carmot_smithing_template',

		'mythicmetals:froge',
		'mythicmetals:doge',

		'mythicmetals:mythril_sword',

		/mythicmetals:.*quadrillum.*/,

		'mythicmetals:durasteel_ore',
		'mythicmetals:durasteel_block',
		'mythicmetals:durasteel_ingot',
		'mythicmetals:durasteel_nugget',
		'mythicmetals:durasteel_sword',
		'mythicmetals:durasteel_axe',
		'mythicmetals:durasteel_shovel',
		'mythicmetals:durasteel_pickaxe',
		'mythicmetals:durasteel_hoe',
		'mythicmetals:durasteel_helmet',
		'mythicmetals:durasteel_chestplate',
		'mythicmetals:durasteel_leggings',
		'mythicmetals:durasteel_boots',

		'mythicmetals:hallowed_nugget',
		'mythicmetals:hallowed_sword',
		'mythicmetals:hallowed_axe',
		'mythicmetals:hallowed_shovel',
		'mythicmetals:hallowed_pickaxe',
		'mythicmetals:hallowed_hoe',
		'mythicmetals:hallowed_helmet',
		'mythicmetals:hallowed_chestplate',
		'mythicmetals:hallowed_leggings',
		'mythicmetals:hallowed_boots',

		'mythicmetals:celestium_nugget',
		'mythicmetals:celestium_sword',
		'mythicmetals:celestium_helmet',
		'mythicmetals:celestium_chestplate',
		'mythicmetals:celestium_leggings',
		'mythicmetals:celestium_boots',

		'mythicmetals:orichalcum_axe',
		'mythicmetals:orichalcum_shovel',
		'mythicmetals:orichalcum_pickaxe',
		'mythicmetals:orichalcum_hoe',

		'mythicmetals:runite_axe',
		'mythicmetals:runite_shovel',
		'mythicmetals:runite_pickaxe',
		'mythicmetals:runite_hoe',
		'mythicmetals:runite_sword',
		/mythicmetals:.*aegis.*/,
		/mythicmetals:.*banglum.*/,
		/mythicmetals:.*_nuke_core/,

		'mythicmetals:osmium_sword',
		'mythicmetals:osmium_axe',
		'mythicmetals:osmium_shovel',
		'mythicmetals:osmium_pickaxe',
		'mythicmetals:osmium_hoe',
		'mythicmetals:osmium_helmet',
		'mythicmetals:osmium_chestplate',
		'mythicmetals:osmium_leggings',
		'mythicmetals:osmium_boots',
		/mythicmetals:.*manganese.*/,
		'mythicmetals:copper_helmet',
		'mythicmetals:copper_chestplate',
		'mythicmetals:copper_leggings',
		'mythicmetals:copper_boots',

		'botania:mana_diamond',
		'botania:mana_diamond_block',
		'botania:manaweave_cloth',
		'botania:mana_string',
		'botania:keep_ivy',
		'botania:thorn_chakram',
		'botania:flare_chakram',
		'botania:mana_fluxfield',
		'botanicadds:elven_fluxfield',
		'botanicadds:flowers/energizera',
		'botanicadds:flowers/floating/energizera',
		'botanicadds:mana_stealer_sword',
		'botania:teru_teru_bozu',
		'botaniacombat:angry_bozu',
		'botaniacombat:mjolnir',
		'botaniacombat:gaia_greatsword',
		'botaniacombat:terrasteel_dagger',
		'botaniacombat:elementium_dagger',
		'botaniacombat:elementium_spear',
		'botaniacombat:soulstaff',
		'botaniacombat:terrasteel_spear',
		'botania:phantom_ink',
		'botania:slime_bottle',
		'botania:light_relay',
		'botania:detector_light_relay',
		'botania:fork_light_relay',
		'botania:toggle_light_relay',
		'botania:light_launcher',
		'botania:star_sword',
		'botanicadds:elvenwood',
		'botanicadds:elvenwood_log',
		'botania:lexica_botania',
		'botania:cosmetic_engineer_goggles',
		'botania:abtruse_platform',
		'botania:spectral_platform',
		'botania:dry_seeds',
		'botania:golden_seeds',
		'botania:vivid_seeds',
		'botania:scorched_seeds',
		'botania:infused_seeds',
		'botania:mutated_seeds',
		'botania:dry_grass',
		'botania:golden_grass',
		'botania:vivid_grass',
		'botania:scorched_grass',
		'botania:infused_grass',
		'botania:mutated_grass',
		'botania:invisibility_cloak',

		'terra_curio:magic_quiver',
		'terra_curio:molten_quiver',
		'terra_curio:stalkers_quiver',
		'terra_curio:cell_phone',
		'terra_curio:tally_counter',
		/terra_curio:.*_watch/,
		'terra_curio:depth_meter',
		'terra_curio:compass',
		'terra_curio:pda',
		'terra_curio:fish_finder',
		'terra_curio:rek_3000',
		'terra_curio:radar',
		'terra_curio:metal_detector',
		'terra_curio:lifeform_analyzer',
		'terra_curio:stopwatch',
		'terra_curio:dps_meter',
		'terra_curio:fishermans_pocket_guide',
		'terra_curio:weather_radio',
		'terra_curio:sextant',
		'terra_curio:gps',
		'terra_curio:goblin_tech',
		'terra_curio:life_form_analyzer',
		'terra_curio:shield_of_cthulhu',
		'terra_curio:tabi',
		'terra_curio:master_ninja_gear',
		'terra_curio:brain_of_confusion',
		'terra_curio:worm_scarf',
		'terra_curio:hive_pack',
		'terra_curio:royal_gel',
		'terra_curio:angler_earring',

		'hammerlib:gears/wooden',
		'hammerlib:gears/stone',
		'hammerlib:gears/copper',
		'hammerlib:gears/iron',
		'hammerlib:gears/gold',
		'hammerlib:gears/diamond',
		'hammerlib:gears/netherite',
		'hammerlib:test_machine',
		'hammerlib:wrench',

		'constructionwand:stone_wand',
		'minecraft:stone_sword',
		'minecraft:stone_pickaxe',
		'minecraft:stone_axe',
		'minecraft:stone_shovel',
		'minecraft:stone_hoe',

		'galosphere:barometer',
		'galosphere:shadow_frame',
		'galosphere:palladium_dust',

		'ftbquests:book',
		'netherdepthsupgrade:lava_fishing_rod',

		'supplementaries:altimeter',
		'supplementaries:wrench',
		'supplementaries:flower_box',

		'create_power_loader:empty_andesite_chunk_loader',
		'create_power_loader:empty_brass_chunk_loader',
		'create:handheld_worldshaper',

		/create:crushed_raw_.*/,

		'farmersdelight:wheat_dough',
		'farmersdelight:rope',
		'farmersdelight:flint_knife',

		'unusualend:phantom_arrow',
		'unusualend:purpur_tank',
		'unusualend:healing_lantern',
		'unusualend:warped_anchor',

		'alloy_forgery:prismarine_bricks_forge_controller',
		'alloy_forgery:bricks_forge_controller',
		'alloy_forgery:stone_bricks_forge_controller',
		'alloy_forgery:deepslate_bricks_forge_controller',
		'alloy_forgery:polished_blackstone_forge_controller',
		'alloy_forgery:end_stone_bricks_forge_controller',
		'alloy_forgery:adamantite_block_forge_controller',

		'alexsmobs:shark_tooth_arrow',
		'alexsmobs:banana',
		'alexscaves:biome_treat',
		'alexscaves:conversion_crucible',
		'alexscaves:beholder',
		/alexscaves:.*sulfur.*/,

		'ars_nouveau:sorcerer_boots',
		'ars_nouveau:sorcerer_leggings',
		'ars_nouveau:sorcerer_robes',
		'ars_nouveau:sorcerer_hood',
		'ars_nouveau:battlemage_boots',
		'ars_nouveau:battlemage_leggings',
		'ars_nouveau:battlemage_robes',
		'ars_nouveau:battlemage_hood',
		'ars_nouveau:ritual_cloudshaping',
		/ars_nouveau:.*sourcelink/,
		'ars_nouveau:worn_notebook',
		'ars_nouveau:glyph_craft',
		'ars_elemental:everfull_urn',

		'nourished_nether:glowing_obsidian',

		'verdantvibes:cattails',

		/functionalstorage:spruce_.*/,
		/functionalstorage:birch_.*/,
		/functionalstorage:jungle_.*/,
		/functionalstorage:dark_oak_.*/,
		/functionalstorage:acacia_.*/,
		/functionalstorage:cherry_.*/,
		/functionalstorage:mangrove_.*/,
		/functionalstorage:crimson_.*/,
		/functionalstorage:warped_.*/,
		/functionalstorage:fluid_.*/,

		/functionalstorage:.*framed_.*/, ,
		'functionalstorage:simple_compacting_drawer',
		'functionalstorage:armory_cabinet',

		'functionalstorage:gold_upgrade',
		'functionalstorage:diamond_upgrade',
		'functionalstorage:netherite_upgrade',
		'functionalstorage:iron_downgrade',

		/simplyswords:mythicmetals_compat\/banglum\/.*/,
		/simplyswords:mythicmetals_compat\/aquarium\/.*/,
		/simplyswords:mythicmetals_compat\/mythril\/.*/,
		/simplyswords:mythicmetals_compat\/carmot\/.*/,
		/simplyswords:mythicmetals_compat\/osmium\/.*/,
		/simplyswords:mythicmetals_compat\/celestium\/.*/,
		/simplyswords:mythicmetals_compat\/quadrillum\/.*/,
		/simplyswords:mythicmetals_compat\/runite\/.*/,
		/simplyswords:mythicmetals_compat\/durasteel\/.*/,

		/simplyswords:.*_longsword/,
		/simplyswords:.*_cutlass/,
		/simplyswords:.*_twinblade/,
		/simplyswords:.*_sai/,
		/simplyswords:.*_rapier/,
		/simplyswords:.*_claymore/,
		/simplyswords:.*_greataxe/,
		/simplyswords:.*_greathammer/,
		/simplyswords:.*_halberd/,

		/simplyswords:runic_.*/,

		'trashcans:energy_trash_can',
		'trashcans:ultimate_trash_can',

		'minecraft:chest',
		'minecraft:trapped_chest',

		/moreburners/,
		'createutilities:void_battery',
		'createutilities:gearcube',

		'etcetera:frame',
		'etcetera:terracotta_vase',
		'etcetera:prickly_can',
		'etcetera:turtle_raft',
		'etcetera:wrench',
		'etcetera:chisel',
		'etcetera:hammer',
		'etcetera:dice',

		'evilcraft:obscured_glass',
		'evilcraft:entangled_chalice',
		'evilcraft:origins_of_darkness',
		'evilcraft:darkened_apple',
		'evilcraft:effortless_ring',
		'evilcraft:corrupted_tear',
		'evilcraft:ender_tear',

		'window_box:bouquet',
		'window_box:topsy_tulip',
		'window_box:floating_topsy_tulip',
		'window_box:snapdresson',
		'window_box:floating_snapdression',
		'window_box:dispelagonium',
		'window_box:floating_dispelagonium',

		/architects_palette:.*board_stairs/,
		/architects_palette:.*board_slab/,
		/architects_palette:.*board_vertical_slab/,

		'architects_palette:charcoal_block',
		'architects_palette:unobtanium',
		/architects_palette:flint_,*/,
		'architects_palette:salmon_scales',
		'architects_palette:cod_scales',
		'architects_palette:salmon_log',
		'architects_palette:cod_log',
		'architects_palette:plating_nub',
		'architects_palette:withered_bone',
		'architects_palette:withered_bone_block',
		'architects_palette:polished_glowstone_nub',
		'architects_palette:scute_block',
		'architects_palette:chiseled_end_stone_bricks',
		/architects_palette:dripstone_brick.*/,
		'architects_palette:dripstone_pillar',
		'architects_palette:chiseled_dripstone',
		/architects_palette:calcite_brick.*/,
		'architects_palette:calcite_pillar',
		'architects_palette:chiseled_calcite',
		/architects_palette:basalt_tile.*/,
		'architects_palette:basalt_pillar',
		'architects_palette:cracked_basalt_tiles',
		'architects_palette:chiseled_basalt_tiles',
		/architects_palette:tuff_brick.*/,
		'architects_palette:tuff_pillar',
		'architects_palette:chiseled_tuff',
		/architects_palette:ancient_plating.*/,
		/architects_palette:.*_nub/,
		/architects_palette:weeping_blackstone.*/,
		/architects_palette:twisting_blackstone.*/,
		/architects_palette:.*heavy.*_bricks.*/,
		'architects_palette:moonshale_flagstone',

		/rehooked/,

		'majruszsdifficulty:wither_sword',
		'majruszsdifficulty:cerberus_fang',
		/majruszsdifficulty:.*infernal_sponge/,

		'cratedelight:sugar_bag',
		'cratedelight:gunpowder_bag',
		'cratedelight:cocoabeans_bag',
		'cratedelight:golden_apple_crate',
		'cratedelight:golden_carrot_crate',
		'cratedelight:glowberry_crate',
		'cratedelight:cod_crate',
		'cratedelight:salmon_crate',
		'cratedelight:cookie_bag',
		'cratedelight:bread_bag',
		'cratedelight:sugar_bag',
		'cratedelight:pumpkin_slice_crate',
		'cratedelight:berry_crate',
		'cratedelight:apple_crate',

		'delightful:acorn',
		'delightful:crystalline_knife',

		'ancient_aether:ancient_dungeon_key',
		'ancient_aether:ancient_sword',
		'ancient_aether:ancient_pendant',
		'ancient_aether:ancient_ring',

		'vinery:dark_cherry_chair',
		'vinery:dark_cherry_table',
		'vinery:dark_cherry_drawer',
		'vinery:dark_cherry_cabinet',
		'vinery:dark_cherry_barrel',
		'vinery:coarse_dirt_slab',
		'vinery:dirt_slab',
		'vinery:grass_slab',
		'vinery:dirt_path_slab',
		'vinery:dark_cherry_shelf',
		'vinery:dark_cherry_big_table',
		'vinery:apple_tree_sapling',
		'vinery:apple_leaves',
		'vinery:apple_bag',
		'vinery:apple_log',
		'vinery:apple_wood',
		'vinery:fermentation_barrel',
		'vinery:apple_juice',
		'vinery:apple_mash',
		'vinery:apple_press',
		'vinery:mead',
		'vinery:jellie_wine',
		'vinery:dark_cherry_floorboards',
		'vinery:dark_cherry_beam',

		/vinery:spruce_wine_rack_.*/,
		/vinery:birch_wine_rack_.*/,
		/vinery:cherry_wine_rack_.*/,
		/vinery:jungle_wine_rack_.*/,
		/vinery:dark_oak_wine_rack_.*/,
		/vinery:acacia_wine_rack_.*/,
		/vinery:mangrove_wine_rack_.*/,
		/vinery:.*_lattice/,

		'vinery:vinery_standard',
		/vinery.*floorboard$/,
		'v_slab_compat:vinery/grass_vertical_slab',
		'v_slab_compat:vinery/coarse_dirt_vertical_slab',
		'v_slab_compat:vinery/dirt_vertical_slab',
		'v_slab_compat:vinery/dirt_path_vertical_slab',
		'vinery:straw_hat',
		/vinery:winemaker_.*/,

		'nethervinery:crimson_fermentation_barrel',
		'nethervinery:crimson_grapevine_pot',
		'nethervinery:crimson_apple_press',
		'nethervinery:crimson_barrel',
		'nethervinery:warped_fermentation_barrel',
		'nethervinery:warped_grapevine_pot',
		'nethervinery:warped_apple_press',
		'nethervinery:warped_barrel',
		'nethervinery:crimson_nether_bag',
		'nethervinery:warped_nether_bag',
		'nethervinery:crested_crimson_planks',
		'nethervinery:crested_warped_planks',
		'nethervinery:reinforced_crimson_planks',
		'nethervinery:reinforced_warped_planks',
		'nethervinery:crimson_bag',
		'nethervinery:warped_bag',

		'beachparty:wet_hay_block',
		'beachparty:palm_glass',
		'beachparty:palm_glass_pane',
		/beachparty:.*thatch.*/,
		'beachparty:sandwaves',
		/beachparty.*floorboard$/,
		'beachparty:completionist_banner',

		'minecraft:copper_nugget',
		'minecraft:copper_leggings',
		'minecraft:copper_helmet',
		'minecraft:copper_chestplate',
		'minecraft:copper_boots',
		'minecraft:copper_pickaxe',
		'minecraft:copper_axe',
		'minecraft:copper_shovel',
		'minecraft:copper_hoe',
		'minecraft:copper_sword',
		'suppsquared:copper_lantern',

		/oreberriesreplanted:.*_bucket/,
		'oreberriesreplanted:copper_nugget',
		/oreberriesreplanted:.*_vat/,
		'oreberriesreplanted:essence_berry',
		'oreberriesreplanted:essence_berry_bush',
		'oreberriesreplanted:nickel_oreberry',
		'oreberriesreplanted:nickel_oreberry_bush',
		'oreberriesreplanted:lead_oreberry',
		'oreberriesreplanted:lead_oreberry_bush',
		'oreberriesreplanted:aluminum_oreberry',
		'oreberriesreplanted:aluminum_oreberry_bush',

		/minecraft:.*_shelf/,

		'accents:hermes_boots',
		'accents:quiver',

		'jumbofurnace:jumbo_furnace',
		'morered:soldering_table',
		'morered:stone_plate',
		'morered:hexidecrubrometer',
		/morered:bitwise_.*/,

		/create:cut_andesite_brick.*/,
		'v_slab_compat:create/cut_andesite_brick_vertical_slab',
		/create:cut_diorite_brick.*/,
		'v_slab_compat:create/cut_diorite_brick_vertical_slab',
		/create:cut_andesite_brick.*/,
		'v_slab_compat:create/cut_andesite_brick_vertical_slab',
		/create:cut_tuff_brick.*/,
		'v_slab_compat:create/cut_tuff_brick_vertical_slab',

		/travelersbackpack:.*_sleeping_bag/,

		'rubinated_nether:runestone',
		'rubinated_nether:rubination_altar',
		'rubinated_nether:ruby_block',
		/rubinated_nether:.*altar_stone.*/,

		/aperture_innovations:concrete_surface/,
		/aperture_innovations:metal_surface/,
		'aperture_innovations:long_fall_boots',
		'aperture_innovations:antline',
		'aperture_innovations:antline_checkmark',
		'aperture_innovations:antline_timer',
		'aperture_innovations:weighted_storage_cube',
		'aperture_innovations:weighted_companion_cube',
		'aperture_innovations:pedestal_button',
		'aperture_innovations:large_button',

		'waxed:ender_wax_block',
		'waxed:cupric_wax_block',
		'waxed:ender_candle',
		'waxed:cupric_candle',
		'waxed:waxed_arid_sand',
		'waxed:waxed_red_arid_sand'
	]
};

global.blacklistedItems = new Set([typeof String]);

function regenerateBlacklist() {
	Item.getTypeList().forEach(id => {
		if (RemovedItems.list.some(entry => {
			if (entry && entry instanceof RegExp) {
				if (entry.test(id)) {
					return true;
				}
				else return false;
			}
			return entry === id;
		})) {
			global.blacklistedItems.add(String(id));
		};
	});

	global.blacklistedItemsArray = Array.from(global.blacklistedItems);

	console.log(`Added ${global.blacklistedItemsArray.length} items to the blacklist`);
}

StartupEvents.postInit(event => {
	regenerateBlacklist();
});

global.isItemDisabled = function (item) {
	let id = (item instanceof Item) ? item.getId() : item;
	return global.blacklistedItems.has(String(id));
};
