JUNGLE_LOOT = false
SPAWN_CRAZED = false
CRAZED_CHANCE = 0.6
MAX_HEIGHT = 10
RANGE_PER_LEVEL = 10
BASE_RANGE = 30
PROTECT_ABOVE = false
DISTANCE_CALC = "CYLINDER"
SPAWN_POWDER = true
DECORATION = true
