attributeReplacements = ["crit_chance = confluence_magic_lib:generic.critical_chance", "ranged_damage = confluence_magic_lib:generic.ranged_damage", "dodge_chance = confluence_magic_lib:generic.dodge_chance", "magic_damage = confluence_magic_lib:generic.magic_damage", "armor_penetration = confluence_magic_lib:generic.armor_penetration"]
modifyTime = -1
version = ""
messageDigest = ""
alarmTimes = -1
itemGroups = true

