
#Xaero's World Map
[xaeroworldmap]
	Enable = true

#Xaero's Minimap
[xaerominimap]
	Enable = true

#Subtle Effects
[subtle_effects]
	Enable = true

#Snow! Real Magic!
[snowrealmagic]
	Enable = true

#In Control
[incontrol]
	Enable = true

