
["Curse of Deterioration"]
	#Toggle Curse of Deterioration
	"Have Curse of Deterioration in game" = true
	#How dameged does the item get after 2 s 
	"How much durability does the item loose" = 1.0

["Curse of Station"]
	#Toggle Curse of Station
	"Have Curse of Station in game" = true
	#How long you need to stand still to get damaged
	"How much does the curse need to have effects" = 10.0
	"Toggle if the anvil damage is possible with Curse of Station" = true
	"Toggle if the quicksand damage is possible with Curse of Station" = true
	"Curse of Station wither skull damagToggle if the wither skull damage is possible with Curse of Statione sequence" = false
	"Toggle if the lightning damage is possible with Curse of Station" = true
	"Toggle if the evoker fang damage is possible with Curse of Station" = true
	"Toggle if the throwing damage is possible with Curse of Station" = true
	"Toggle if silverfish damage is possible with Curse of Station" = true
	"Toggle if dragon damage is possible with Curse of Station" = true
	"Toggle if explosion damage is possible with Curse of Station" = true

["Curse of Teleportation"]
	#Toggle Curse of Teleportation
	"Have Curse of Teleportation in game " = true
	#How far chan Curse of Teleportation get you
	"How far can you be telepoted" = 8.0

["Curse of Notice"]
	#Toggle Curse of Notice
	"Have Curse of Notice in game " = true
	#Sets the range in witch aggressive mobs will target you
	"How far aggressive mobs will notice you" = 48.0
	#Sets the range in witch neutral mobs will target you
	"How far neutral mobs will notice you" = 24.0

["Curse of Apnea"]
	#Toggle Curse of Apnea
	"Have Curse of Apnea in game" = true
	#The damage that curse of apnea does to you if you are suffocating
	"How much damage you take while suffocating" = 1.0

["Curse of Flammability "]
	#Toggle Curse of Flammability
	"Have Curse of Flammability in game" = true

["Curse of Disorder"]
	#Toggle Curse of Disorder
	"Have Curse of Disorder in game " = true
	#How often in you inventory something gets messed up
	"How often an item gets switched up" = 30.0

["Curse of Frost Imprisonment"]
	#Toggle Curse of Frost Imprisonment
	"Have Curse of Frost Imprisonment in game" = true

["Curse of Betrayal"]
	#Toggle Curse of Betrayal
	"Have Curse of Betrayal in game" = true
	#How often you will get betrayed by your shied
	"1/(you choose) probability of getting betrayed" = 4.0

["Curse of Zone "]
	#Toggle Curse of Zone
	"Have Curse of Zone in game" = true
	#The zone in witch Curse of Zone will make you keep your item
	"The Zone of Curse of Zone" = 400.0

["Curse of The Golden Touch"]
	#Toggle Curse of The Goden Touch
	"Have Curse of The Golden Touch" = true
	#Sets the damage that the item needs to take to become gilding
	"When does it become gilding" = 200.0
	#Sets the damage that the item needs to take to become gilded
	"When does it become gilded" = 400.0

["Curse of Voiding"]
	#Toggle Curse of Voiding in game
	"Have Curse of Voiding in game" = false

["Curse of Movement"]
	#Toggle Curse of Movement in game
	"Have Curse of Movement in game" = true
	#Sets the destruction attribute for the item with Curse of Movement
	"How fast does your Curse of Movement item break" = 1.0

["Curse of Floating"]
	#Toggle Curse of Floating in game
	"Have Curse of Floating in game" = true

["Curse of Hordes"]
	#Toggle Curse of Hordes in game
	"Have Curse of Hordes in game" = true
	#Your imput / the mob's max health is the probability that a new mob will spawn
	"How often does a new mob spawn" = 5.0
	#The maximum health that a mob needs to have to be affected by Curse of Hordes
	"The max health of Curse of Hordes Affected mobs" = 40.0

["Curse of Withering"]
	#Toggle Curse of Withering in game
	"Have Curse of Floating in gameHave Curse of Withering in game" = true
	#How many hearts does Curse of Withering remove
	"Health points loss by Curse of Withering" = 4.0
	#The range in witch Curse of Wither can affect mobs
	"How far can mobs get Curse of Wither effects" = 10.0
	#The moltiplicator for the range of blocks affected by Curse of Withering
	"How far blocks can be affected by Curse of Withering" = 1.0

