# Don't change this! Version used to track needed updates.
version = 1
disableParticles = false
maxParticlesPerSheet = 16384
particleRenderDistanceMultiplier = 1.0
asynchronousTicking = true
reduceAllChance = 0.0
reduceDecreasedChance = 0.0
turnOffPotionParticlesV2 = [
    "SELF"
]

[byTypeReductions]
"minecraft:damage_indicator" = 0.0
"minecraft:effect" = 0.7973856209150325
"minecraft:ambient_entity_effect" = 0.803921568627451
"minecraft:entity_effect" = 0.803921568627451
"majruszsdifficulty:blood" = 0.5032679738562089