
# Shadow Drop: Client Configuration
# (check the mod page for more information on compatibility with other mods)
#
[general]
	# Enable/disable the mod entirely
	modEnabled = true
	#
	# Shadow color (RGB hex)
	shadowColor = "#000000"
	#
	# Shadow opacity (255 is fully opaque)
	#Range: 0 ~ 255
	shadowAlpha = 99
	#
	# Shadow X offset
	#Range: 0 ~ 4
	shadowXOffset = 1
	#
	# Shadow Y offset
	#Range: 0 ~ 4
	shadowYOffset = 1
	#
	# Items are offset towards the camera to ensure space behind them for shadows
	# Disable if items are rendering above things they shouldn't
	offsetItems = true

[shadowContexts]
	# Items always have shadows (overrules other shadow contexts when true)
	shadowsAlways = true
	#
	# Items in slots (see slot detection config) have shadows
	shadowsInSlots = false
	#
	# Items in hotbar slots always have shadows
	shadowsInHotbar = false
	#
	# Items being carried by the cursor have shadows
	shadowsInCursor = false

[cropContexts]
	# Shadows of items in slots (see slot detection config) should be cropped
	cropToSlots = false
	#
	# Shadows of items in the hotbar should always be cropped
	cropToHotbar = false
	#
	# Shadows of items under the cursor should be uncropped
	uncropUnderCursor = false

[slotDetection]
	# RGB hex colors for detection of visual slots (e.g. "#FFFFFF")
	# This color is searched for in the bottom-right corner pixel wherever an item is rendered
	# Adjust for compatibility with resource packs or modded GUIs where this pixel is not #FFFFFF
	slotBrColors = ["#FFFFFF"]

[exceptions]
	# Items with half shadow alpha (e.g. "#forge:glass", "minecraft:glass")
	translucentItems = ["#forge:glass", "#forge:glass_panes", "minecraft:beacon"]
	#
	# Items with no shadow (e.g. "#forge:glass", "minecraft:glass")
	transparentItems = []

[experimental]
	# EXPERIMENTAL: force refresh of depth buffer when rendering shadows
	# Fixes shadow rendering in some places (such as square shadows or shadows overlapping incorrectly)
	# May however break rendering elsewhere
	forceDepthRefresh = false

