#Key Adapters
#Thu Sep 10 19:44:45 CEST 2026
key.rehooked.remove_all_hooks_key=
keybinds.combatroll.roll=
key.open_menu=
key.baublemounts.mountsummon=
key.rehooked.retract_hook_key=
key.rehooked.fire_hook_key=
