StartupEvents.registry('banner_pattern', registry => {

	const $BannerPattern = Java.loadClass('net.minecraft.world.level.block.entity.BannerPattern');
	function registerBannerPattern(id, tag, name) {
		console.log(`Registering banner pattern kubejs:${id}`)
		registry.createCustom(id, () => new $BannerPattern(id)).tag(global.getOrDefault(tag, 'minecraft:no_item_required'));

		Color.DYE.forEach(color => global.addTranslation(
			`block.minecraft.banner.kubejs.${id}.${color}`,
			`${global.toTitleCase(global.textReplaceAll(color, '_', ' '))} ${global.getOrDefault(name, global.toTitleCase(global.textReplaceAll(id.split('/')[1], '_', ' ')))}`
		));
	}

	registerBannerPattern('moxvallix/chequered');
	registerBannerPattern('moxvallix/circle_tiles');
	registerBannerPattern('moxvallix/cogs');
	registerBannerPattern('moxvallix/curtains');
	registerBannerPattern('moxvallix/double_bars');
	registerBannerPattern('moxvallix/double_gradient');
	registerBannerPattern('moxvallix/fancy');
	registerBannerPattern('moxvallix/tattered');

	registerBannerPattern('muki/25_fade');
	registerBannerPattern('muki/bend_tilted_sinister');
	registerBannerPattern('muki/bend_tilted');
	registerBannerPattern('muki/billet_bottom');
	registerBannerPattern('muki/billet_center');
	registerBannerPattern('muki/billet_left');
	registerBannerPattern('muki/billet_right');
	registerBannerPattern('muki/billet_top');
	registerBannerPattern('muki/bordure_center');
	registerBannerPattern('muki/bordure_corners');
	registerBannerPattern('muki/bottom_keystone_down');
	registerBannerPattern('muki/bottom_keystone_up');
	registerBannerPattern('muki/checkered_inverted');
	registerBannerPattern('muki/checkered');
	registerBannerPattern('muki/gradient_left');
	registerBannerPattern('muki/gradient_right');
	registerBannerPattern('muki/left_chevron');
	registerBannerPattern('muki/left_indented');
	registerBannerPattern('muki/quad_bezants');
	registerBannerPattern('muki/quarter_bottom_left');
	registerBannerPattern('muki/quarter_bottom_right');
	registerBannerPattern('muki/quarter_top_left');
	registerBannerPattern('muki/quarter_top_right');
	registerBannerPattern('muki/right_chevron');
	registerBannerPattern('muki/right_indented');
	registerBannerPattern('muki/top_keystone_down');
	registerBannerPattern('muki/top_keystone_up');

	registerBannerPattern('moxvallix/blam', 'minecraft:pattern_item/creeper');
	registerBannerPattern('moxvallix/ghast', 'minecraft:pattern_item/creeper');
	registerBannerPattern('moxvallix/pillager', 'minecraft:pattern_item/creeper');
	registerBannerPattern('moxvallix/ribs', 'minecraft:pattern_item/creeper');
	registerBannerPattern('moxvallix/villager', 'minecraft:pattern_item/creeper');

	registerBannerPattern('moxvallix/knot', 'minecraft:pattern_item/flower');
	registerBannerPattern('moxvallix/moon', 'minecraft:pattern_item/flower');
	registerBannerPattern('moxvallix/peace', 'minecraft:pattern_item/flower');
	registerBannerPattern('moxvallix/sun', 'minecraft:pattern_item/flower');
	registerBannerPattern('moxvallix/yin_yang', 'minecraft:pattern_item/flower');

	registerBannerPattern('moxvallix/horn', 'minecraft:pattern_item/globe');
	registerBannerPattern('moxvallix/pumpkin', 'minecraft:pattern_item/globe');

	registerBannerPattern('moxvallix/anchor', 'minecraft:pattern_item/thing');
	registerBannerPattern('moxvallix/clubs', 'minecraft:pattern_item/thing');
	registerBannerPattern('moxvallix/companion', 'minecraft:pattern_item/thing');
	registerBannerPattern('moxvallix/diamonds', 'minecraft:pattern_item/thing');
	registerBannerPattern('moxvallix/emoji', 'minecraft:pattern_item/thing');
	registerBannerPattern('moxvallix/eye', 'minecraft:pattern_item/thing');
	registerBannerPattern('moxvallix/hearts', 'minecraft:pattern_item/thing');
	registerBannerPattern('moxvallix/revolution', 'minecraft:pattern_item/thing');
	registerBannerPattern('moxvallix/spades', 'minecraft:pattern_item/thing');

	registerBannerPattern('moxvallix/castle', 'minecraft:pattern_item/snout');
	registerBannerPattern('moxvallix/palace', 'minecraft:pattern_item/snout');
	registerBannerPattern('moxvallix/pyramid', 'minecraft:pattern_item/snout');
	registerBannerPattern('moxvallix/tower', 'minecraft:pattern_item/snout');

	registerBannerPattern('moxvallix/crown', 'minecraft:pattern_item/skull');
	registerBannerPattern('moxvallix/hammer', 'minecraft:pattern_item/skull');
	registerBannerPattern('moxvallix/shield', 'minecraft:pattern_item/skull');
	registerBannerPattern('moxvallix/sword', 'minecraft:pattern_item/skull');
	registerBannerPattern('moxvallix/trident', 'minecraft:pattern_item/skull');

	registerBannerPattern('snuzzle/text/a', 'adj:pattern_item/text', '"a"');
	registerBannerPattern('snuzzle/text/b', 'adj:pattern_item/text', '"b"');
	registerBannerPattern('snuzzle/text/c', 'adj:pattern_item/text', '"c"');
	registerBannerPattern('snuzzle/text/d', 'adj:pattern_item/text', '"d"');
	registerBannerPattern('snuzzle/text/e', 'adj:pattern_item/text', '"e"');
	registerBannerPattern('snuzzle/text/f', 'adj:pattern_item/text', '"f"');
	registerBannerPattern('snuzzle/text/g', 'adj:pattern_item/text', '"g"');
	registerBannerPattern('snuzzle/text/h', 'adj:pattern_item/text', '"h"');
	registerBannerPattern('snuzzle/text/i', 'adj:pattern_item/text', '"i"');
	registerBannerPattern('snuzzle/text/j', 'adj:pattern_item/text', '"j"');
	registerBannerPattern('snuzzle/text/k', 'adj:pattern_item/text', '"k"');
	registerBannerPattern('snuzzle/text/l', 'adj:pattern_item/text', '"l"');
	registerBannerPattern('snuzzle/text/m', 'adj:pattern_item/text', '"m"');
	registerBannerPattern('snuzzle/text/n', 'adj:pattern_item/text', '"n"');
	registerBannerPattern('snuzzle/text/o', 'adj:pattern_item/text', '"o"');
	registerBannerPattern('snuzzle/text/p', 'adj:pattern_item/text', '"p"');
	registerBannerPattern('snuzzle/text/q', 'adj:pattern_item/text', '"q"');
	registerBannerPattern('snuzzle/text/r', 'adj:pattern_item/text', '"r"');
	registerBannerPattern('snuzzle/text/s', 'adj:pattern_item/text', '"s"');
	registerBannerPattern('snuzzle/text/t', 'adj:pattern_item/text', '"t"');
	registerBannerPattern('snuzzle/text/u', 'adj:pattern_item/text', '"u"');
	registerBannerPattern('snuzzle/text/v', 'adj:pattern_item/text', '"v"');
	registerBannerPattern('snuzzle/text/w', 'adj:pattern_item/text', '"w"');
	registerBannerPattern('snuzzle/text/x', 'adj:pattern_item/text', '"x"');
	registerBannerPattern('snuzzle/text/y', 'adj:pattern_item/text', '"y"');
	registerBannerPattern('snuzzle/text/z', 'adj:pattern_item/text', '"z"');

	registerBannerPattern('snuzzle/text_caps/a', 'adj:pattern_item/text', '"A"');
	registerBannerPattern('snuzzle/text_caps/b', 'adj:pattern_item/text', '"B"');
	registerBannerPattern('snuzzle/text_caps/c', 'adj:pattern_item/text', '"C"');
	registerBannerPattern('snuzzle/text_caps/d', 'adj:pattern_item/text', '"D"');
	registerBannerPattern('snuzzle/text_caps/e', 'adj:pattern_item/text', '"E"');
	registerBannerPattern('snuzzle/text_caps/f', 'adj:pattern_item/text', '"F"');
	registerBannerPattern('snuzzle/text_caps/g', 'adj:pattern_item/text', '"G"');
	registerBannerPattern('snuzzle/text_caps/h', 'adj:pattern_item/text', '"H"');
	registerBannerPattern('snuzzle/text_caps/i', 'adj:pattern_item/text', '"I"');
	registerBannerPattern('snuzzle/text_caps/j', 'adj:pattern_item/text', '"J"');
	registerBannerPattern('snuzzle/text_caps/k', 'adj:pattern_item/text', '"K"');
	registerBannerPattern('snuzzle/text_caps/l', 'adj:pattern_item/text', '"L"');
	registerBannerPattern('snuzzle/text_caps/m', 'adj:pattern_item/text', '"M"');
	registerBannerPattern('snuzzle/text_caps/n', 'adj:pattern_item/text', '"N"');
	registerBannerPattern('snuzzle/text_caps/o', 'adj:pattern_item/text', '"O"');
	registerBannerPattern('snuzzle/text_caps/p', 'adj:pattern_item/text', '"P"');
	registerBannerPattern('snuzzle/text_caps/q', 'adj:pattern_item/text', '"Q"');
	registerBannerPattern('snuzzle/text_caps/r', 'adj:pattern_item/text', '"R"');
	registerBannerPattern('snuzzle/text_caps/s', 'adj:pattern_item/text', '"S"');
	registerBannerPattern('snuzzle/text_caps/t', 'adj:pattern_item/text', '"T"');
	registerBannerPattern('snuzzle/text_caps/u', 'adj:pattern_item/text', '"U"');
	registerBannerPattern('snuzzle/text_caps/v', 'adj:pattern_item/text', '"V"');
	registerBannerPattern('snuzzle/text_caps/w', 'adj:pattern_item/text', '"W"');
	registerBannerPattern('snuzzle/text_caps/x', 'adj:pattern_item/text', '"X"');
	registerBannerPattern('snuzzle/text_caps/y', 'adj:pattern_item/text', '"Y"');
	registerBannerPattern('snuzzle/text_caps/z', 'adj:pattern_item/text', '"Z"');

	registerBannerPattern('snuzzle/text_accents/a_acute', 'adj:pattern_item/text', '"á"');
	registerBannerPattern('snuzzle/text_accents/a_circumflex', 'adj:pattern_item/text', '"â"');
	registerBannerPattern('snuzzle/text_accents/a_diaeresis', 'adj:pattern_item/text', '"ä"');
	registerBannerPattern('snuzzle/text_accents/a_grave', 'adj:pattern_item/text', '"à"');
	registerBannerPattern('snuzzle/text_accents/a_ogonek', 'adj:pattern_item/text', '"ą"');
	registerBannerPattern('snuzzle/text_accents/a_ring', 'adj:pattern_item/text', '"å"');
	registerBannerPattern('snuzzle/text_accents/ae_ligature', 'adj:pattern_item/text', '"æ"');
	registerBannerPattern('snuzzle/text_accents/c_acute', 'adj:pattern_item/text', '"ć"');
	registerBannerPattern('snuzzle/text_accents/c_cedil', 'adj:pattern_item/text', '"ç"');
	registerBannerPattern('snuzzle/text_accents/e_acute', 'adj:pattern_item/text', '"é"');
	registerBannerPattern('snuzzle/text_accents/e_circumflex', 'adj:pattern_item/text', '"ê"');
	registerBannerPattern('snuzzle/text_accents/e_diaeresis', 'adj:pattern_item/text', '"ë"');
	registerBannerPattern('snuzzle/text_accents/e_grave', 'adj:pattern_item/text', '"è"');
	registerBannerPattern('snuzzle/text_accents/e_ogonek', 'adj:pattern_item/text', '"ę"');
	registerBannerPattern('snuzzle/text_accents/eszett', 'adj:pattern_item/text', '"ß"');
	registerBannerPattern('snuzzle/text_accents/i_acute', 'adj:pattern_item/text', '"í"');
	registerBannerPattern('snuzzle/text_accents/i_circumflex', 'adj:pattern_item/text', '"î"');
	registerBannerPattern('snuzzle/text_accents/i_diaeresis', 'adj:pattern_item/text', '"ï"');
	registerBannerPattern('snuzzle/text_accents/ij_digraph', 'adj:pattern_item/text', '"ij"');
	registerBannerPattern('snuzzle/text_accents/l_stroke', 'adj:pattern_item/text', '"ł"');
	registerBannerPattern('snuzzle/text_accents/n_acute', 'adj:pattern_item/text', '"ń"');
	registerBannerPattern('snuzzle/text_accents/n_tilde', 'adj:pattern_item/text', '"ñ"');
	registerBannerPattern('snuzzle/text_accents/o_acute', 'adj:pattern_item/text', '"ó"');
	registerBannerPattern('snuzzle/text_accents/o_circumflex', 'adj:pattern_item/text', '"ô"');
	registerBannerPattern('snuzzle/text_accents/o_diaeresis', 'adj:pattern_item/text', '"ö"');
	registerBannerPattern('snuzzle/text_accents/o_slash', 'adj:pattern_item/text', '"ø"');
	registerBannerPattern('snuzzle/text_accents/oe_ligature', 'adj:pattern_item/text', '"œ"');
	registerBannerPattern('snuzzle/text_accents/s_acute', 'adj:pattern_item/text', '"ś"');
	registerBannerPattern('snuzzle/text_accents/u_acute', 'adj:pattern_item/text', '"ú"');
	registerBannerPattern('snuzzle/text_accents/u_circumflex', 'adj:pattern_item/text', '"û"');
	registerBannerPattern('snuzzle/text_accents/u_diaeresis', 'adj:pattern_item/text', '"ü"');
	registerBannerPattern('snuzzle/text_accents/u_grave', 'adj:pattern_item/text', '"ù"');
	registerBannerPattern('snuzzle/text_accents/y_diaeresis', 'adj:pattern_item/text', '"ÿ"');
	registerBannerPattern('snuzzle/text_accents/z_acute', 'adj:pattern_item/text', '"ź"');
	registerBannerPattern('snuzzle/text_accents/z_overdot', 'adj:pattern_item/text', '"ż"');

	registerBannerPattern('snuzzle/text_accents_caps/a_acute', 'adj:pattern_item/text', '"Á"');
	registerBannerPattern('snuzzle/text_accents_caps/a_circumflex', 'adj:pattern_item/text', '"Â"');
	registerBannerPattern('snuzzle/text_accents_caps/a_diaeresis', 'adj:pattern_item/text', '"Ä"');
	registerBannerPattern('snuzzle/text_accents_caps/a_grave', 'adj:pattern_item/text', '"À"');
	registerBannerPattern('snuzzle/text_accents_caps/a_ogonek', 'adj:pattern_item/text', '"Ą"');
	registerBannerPattern('snuzzle/text_accents_caps/a_ring', 'adj:pattern_item/text', '"Å"');
	registerBannerPattern('snuzzle/text_accents_caps/ae_ligature', 'adj:pattern_item/text', '"Æ"');
	registerBannerPattern('snuzzle/text_accents_caps/c_acute', 'adj:pattern_item/text', '"Ć"');
	registerBannerPattern('snuzzle/text_accents_caps/c_cedil', 'adj:pattern_item/text', '"Ç"');
	registerBannerPattern('snuzzle/text_accents_caps/e_acute', 'adj:pattern_item/text', '"É"');
	registerBannerPattern('snuzzle/text_accents_caps/e_circumflex', 'adj:pattern_item/text', '"Ê"');
	registerBannerPattern('snuzzle/text_accents_caps/e_diaeresis', 'adj:pattern_item/text', '"Ë"');
	registerBannerPattern('snuzzle/text_accents_caps/e_grave', 'adj:pattern_item/text', '"È"');
	registerBannerPattern('snuzzle/text_accents_caps/e_ogonek', 'adj:pattern_item/text', '"Ę"');
	registerBannerPattern('snuzzle/text_accents_caps/eszett', 'adj:pattern_item/text', '"ẞ"');
	registerBannerPattern('snuzzle/text_accents_caps/i_acute', 'adj:pattern_item/text', '"Í"');
	registerBannerPattern('snuzzle/text_accents_caps/i_circumflex', 'adj:pattern_item/text', '"Î"');
	registerBannerPattern('snuzzle/text_accents_caps/i_diaeresis', 'adj:pattern_item/text', '"Ï"');
	registerBannerPattern('snuzzle/text_accents_caps/ij_digraph', 'adj:pattern_item/text', '"IJ"');
	registerBannerPattern('snuzzle/text_accents_caps/l_stroke', 'adj:pattern_item/text', '"Ł"');
	registerBannerPattern('snuzzle/text_accents_caps/n_acute', 'adj:pattern_item/text', '"Ń"');
	registerBannerPattern('snuzzle/text_accents_caps/n_tilde', 'adj:pattern_item/text', '"Ñ"');
	registerBannerPattern('snuzzle/text_accents_caps/o_acute', 'adj:pattern_item/text', '"Ó"');
	registerBannerPattern('snuzzle/text_accents_caps/o_circumflex', 'adj:pattern_item/text', '"Ô"');
	registerBannerPattern('snuzzle/text_accents_caps/o_diaeresis', 'adj:pattern_item/text', '"Ö"');
	registerBannerPattern('snuzzle/text_accents_caps/o_slash', 'adj:pattern_item/text', '"Ø"');
	registerBannerPattern('snuzzle/text_accents_caps/oe_ligature', 'adj:pattern_item/text', '"Œ"');
	registerBannerPattern('snuzzle/text_accents_caps/s_acute', 'adj:pattern_item/text', '"Ś"');
	registerBannerPattern('snuzzle/text_accents_caps/u_acute', 'adj:pattern_item/text', '"Ú"');
	registerBannerPattern('snuzzle/text_accents_caps/u_circumflex', 'adj:pattern_item/text', '"Û"');
	registerBannerPattern('snuzzle/text_accents_caps/u_diaeresis', 'adj:pattern_item/text', '"Ü"');
	registerBannerPattern('snuzzle/text_accents_caps/u_grave', 'adj:pattern_item/text', '"Ù"');
	registerBannerPattern('snuzzle/text_accents_caps/y_diaeresis', 'adj:pattern_item/text', '"Ÿ"');
	registerBannerPattern('snuzzle/text_accents_caps/z_acute', 'adj:pattern_item/text', '"Ź"');
	registerBannerPattern('snuzzle/text_accents_caps/z_overdot', 'adj:pattern_item/text', '"Ż"');

	registerBannerPattern('snuzzle/text_numbers/0', 'adj:pattern_item/text', '"0"');
	registerBannerPattern('snuzzle/text_numbers/1', 'adj:pattern_item/text', '"1"');
	registerBannerPattern('snuzzle/text_numbers/2', 'adj:pattern_item/text', '"2"');
	registerBannerPattern('snuzzle/text_numbers/3', 'adj:pattern_item/text', '"3"');
	registerBannerPattern('snuzzle/text_numbers/4', 'adj:pattern_item/text', '"4"');
	registerBannerPattern('snuzzle/text_numbers/5', 'adj:pattern_item/text', '"5"');
	registerBannerPattern('snuzzle/text_numbers/6', 'adj:pattern_item/text', '"6"');
	registerBannerPattern('snuzzle/text_numbers/7', 'adj:pattern_item/text', '"7"');
	registerBannerPattern('snuzzle/text_numbers/8', 'adj:pattern_item/text', '"8"');
	registerBannerPattern('snuzzle/text_numbers/9', 'adj:pattern_item/text', '"9"');

	registerBannerPattern('snuzzle/text_symbols/ampersand', 'adj:pattern_item/text', '"&"');
	registerBannerPattern('snuzzle/text_symbols/apostrophe', 'adj:pattern_item/text', '"\'"');
	registerBannerPattern('snuzzle/text_symbols/asterisk', 'adj:pattern_item/text', '"*"');
	registerBannerPattern('snuzzle/text_symbols/at', 'adj:pattern_item/text', '"@"');
	registerBannerPattern('snuzzle/text_symbols/backslash', 'adj:pattern_item/text', '"\\\\"');
	registerBannerPattern('snuzzle/text_symbols/brace_left', 'adj:pattern_item/text', '"{"');
	registerBannerPattern('snuzzle/text_symbols/brace_right', 'adj:pattern_item/text', '"}"');
	registerBannerPattern('snuzzle/text_symbols/bracket_left', 'adj:pattern_item/text', '"["');
	registerBannerPattern('snuzzle/text_symbols/bracket_right', 'adj:pattern_item/text', '"]"');
	registerBannerPattern('snuzzle/text_symbols/caret', 'adj:pattern_item/text', '"^"');
	registerBannerPattern('snuzzle/text_symbols/colon', 'adj:pattern_item/text', '":"');
	registerBannerPattern('snuzzle/text_symbols/comma', 'adj:pattern_item/text', '","');
	registerBannerPattern('snuzzle/text_symbols/copyright', 'adj:pattern_item/text', '"©"');
	registerBannerPattern('snuzzle/text_symbols/degree', 'adj:pattern_item/text', '"°"');
	registerBannerPattern('snuzzle/text_symbols/divide', 'adj:pattern_item/text', '"÷"');
	registerBannerPattern('snuzzle/text_symbols/dollar', 'adj:pattern_item/text', '"$"');
	registerBannerPattern('snuzzle/text_symbols/double_quote_left', 'adj:pattern_item/text', '"“"');
	registerBannerPattern('snuzzle/text_symbols/double_quote_right', 'adj:pattern_item/text', '"”"');
	registerBannerPattern('snuzzle/text_symbols/ellipsis', 'adj:pattern_item/text', '"…"');
	registerBannerPattern('snuzzle/text_symbols/equal', 'adj:pattern_item/text', '"="');
	registerBannerPattern('snuzzle/text_symbols/exclamation', 'adj:pattern_item/text', '"!"');
	registerBannerPattern('snuzzle/text_symbols/greater', 'adj:pattern_item/text', '">"');
	registerBannerPattern('snuzzle/text_symbols/hash', 'adj:pattern_item/text', '"#"');
	registerBannerPattern('snuzzle/text_symbols/hyphen', 'adj:pattern_item/text', '"-"');
	registerBannerPattern('snuzzle/text_symbols/iexclamation', 'adj:pattern_item/text', '"¡"');
	registerBannerPattern('snuzzle/text_symbols/iquestion', 'adj:pattern_item/text', '"¿"');
	registerBannerPattern('snuzzle/text_symbols/left_parenthesis', 'adj:pattern_item/text', '"("');
	registerBannerPattern('snuzzle/text_symbols/lessthan', 'adj:pattern_item/text', '"<"');
	registerBannerPattern('snuzzle/text_symbols/percent', 'adj:pattern_item/text', '"%"');
	registerBannerPattern('snuzzle/text_symbols/period', 'adj:pattern_item/text', '"."');
	registerBannerPattern('snuzzle/text_symbols/plus', 'adj:pattern_item/text', '"+"');
	registerBannerPattern('snuzzle/text_symbols/question', 'adj:pattern_item/text', '"?"');
	registerBannerPattern('snuzzle/text_symbols/quote', 'adj:pattern_item/text', '"\\""');
	registerBannerPattern('snuzzle/text_symbols/registered', 'adj:pattern_item/text', '"®"');
	registerBannerPattern('snuzzle/text_symbols/right_parenthesis', 'adj:pattern_item/text', '")"');
	registerBannerPattern('snuzzle/text_symbols/semicolon', 'adj:pattern_item/text', '";"');
	registerBannerPattern('snuzzle/text_symbols/single_quote_left', 'adj:pattern_item/text', '"‘"');
	registerBannerPattern('snuzzle/text_symbols/single_quote_right', 'adj:pattern_item/text', '"’"');
	registerBannerPattern('snuzzle/text_symbols/slash', 'adj:pattern_item/text', '"/"');
	registerBannerPattern('snuzzle/text_symbols/tilde', 'adj:pattern_item/text', '"~"');
	registerBannerPattern('snuzzle/text_symbols/times', 'adj:pattern_item/text', '"×"');
	registerBannerPattern('snuzzle/text_symbols/trademark', 'adj:pattern_item/text', '"™"');
	registerBannerPattern('snuzzle/text_symbols/underscore', 'adj:pattern_item/text', '"_"');
	registerBannerPattern('snuzzle/text_symbols/vertical_bar', 'adj:pattern_item/text', '"|"');

	registerBannerPattern('snuzzle/text_galactic/a', 'minecraft:pattern_item/thing', '""');
	registerBannerPattern('snuzzle/text_galactic/b', 'minecraft:pattern_item/thing', '""');
	registerBannerPattern('snuzzle/text_galactic/c', 'minecraft:pattern_item/thing', '""');
	registerBannerPattern('snuzzle/text_galactic/d', 'minecraft:pattern_item/thing', '""');
	registerBannerPattern('snuzzle/text_galactic/e', 'minecraft:pattern_item/thing', '""');
	registerBannerPattern('snuzzle/text_galactic/f', 'minecraft:pattern_item/thing', '""');
	registerBannerPattern('snuzzle/text_galactic/g', 'minecraft:pattern_item/thing', '""');
	registerBannerPattern('snuzzle/text_galactic/h', 'minecraft:pattern_item/thing', '""');
	registerBannerPattern('snuzzle/text_galactic/i', 'minecraft:pattern_item/thing', '""');
	registerBannerPattern('snuzzle/text_galactic/j', 'minecraft:pattern_item/thing', '""');
	registerBannerPattern('snuzzle/text_galactic/k', 'minecraft:pattern_item/thing', '""');
	registerBannerPattern('snuzzle/text_galactic/l', 'minecraft:pattern_item/thing', '""');
	registerBannerPattern('snuzzle/text_galactic/m', 'minecraft:pattern_item/thing', '""');
	registerBannerPattern('snuzzle/text_galactic/n', 'minecraft:pattern_item/thing', '""');
	registerBannerPattern('snuzzle/text_galactic/o', 'minecraft:pattern_item/thing', '""');
	registerBannerPattern('snuzzle/text_galactic/p', 'minecraft:pattern_item/thing', '""');
	registerBannerPattern('snuzzle/text_galactic/q', 'minecraft:pattern_item/thing', '""');
	registerBannerPattern('snuzzle/text_galactic/r', 'minecraft:pattern_item/thing', '""');
	registerBannerPattern('snuzzle/text_galactic/s', 'minecraft:pattern_item/thing', '""');
	registerBannerPattern('snuzzle/text_galactic/t', 'minecraft:pattern_item/thing', '""');
	registerBannerPattern('snuzzle/text_galactic/u', 'minecraft:pattern_item/thing', '""');
	registerBannerPattern('snuzzle/text_galactic/v', 'minecraft:pattern_item/thing', '""');
	registerBannerPattern('snuzzle/text_galactic/w', 'minecraft:pattern_item/thing', '""');
	registerBannerPattern('snuzzle/text_galactic/x', 'minecraft:pattern_item/thing', '""');
	registerBannerPattern('snuzzle/text_galactic/y', 'minecraft:pattern_item/thing', '""');
	registerBannerPattern('snuzzle/text_galactic/z', 'minecraft:pattern_item/thing', '""');

	registerBannerPattern('snuzzle/text_illager/a', 'minecraft:pattern_item/thing', '""');
	registerBannerPattern('snuzzle/text_illager/b', 'minecraft:pattern_item/thing', '""');
	registerBannerPattern('snuzzle/text_illager/c', 'minecraft:pattern_item/thing', '""');
	registerBannerPattern('snuzzle/text_illager/d', 'minecraft:pattern_item/thing', '""');
	registerBannerPattern('snuzzle/text_illager/e', 'minecraft:pattern_item/thing', '""');
	registerBannerPattern('snuzzle/text_illager/f', 'minecraft:pattern_item/thing', '""');
	registerBannerPattern('snuzzle/text_illager/g', 'minecraft:pattern_item/thing', '""');
	registerBannerPattern('snuzzle/text_illager/h', 'minecraft:pattern_item/thing', '""');
	registerBannerPattern('snuzzle/text_illager/i', 'minecraft:pattern_item/thing', '""');
	registerBannerPattern('snuzzle/text_illager/j', 'minecraft:pattern_item/thing', '""');
	registerBannerPattern('snuzzle/text_illager/k', 'minecraft:pattern_item/thing', '""');
	registerBannerPattern('snuzzle/text_illager/l', 'minecraft:pattern_item/thing', '""');
	registerBannerPattern('snuzzle/text_illager/m', 'minecraft:pattern_item/thing', '""');
	registerBannerPattern('snuzzle/text_illager/n', 'minecraft:pattern_item/thing', '""');
	registerBannerPattern('snuzzle/text_illager/o', 'minecraft:pattern_item/thing', '""');
	registerBannerPattern('snuzzle/text_illager/p', 'minecraft:pattern_item/thing', '""');
	registerBannerPattern('snuzzle/text_illager/q', 'minecraft:pattern_item/thing', '""');
	registerBannerPattern('snuzzle/text_illager/r', 'minecraft:pattern_item/thing', '""');
	registerBannerPattern('snuzzle/text_illager/s', 'minecraft:pattern_item/thing', '""');
	registerBannerPattern('snuzzle/text_illager/t', 'minecraft:pattern_item/thing', '""');
	registerBannerPattern('snuzzle/text_illager/u', 'minecraft:pattern_item/thing', '""');
	registerBannerPattern('snuzzle/text_illager/v', 'minecraft:pattern_item/thing', '""');
	registerBannerPattern('snuzzle/text_illager/w', 'minecraft:pattern_item/thing', '""');
	registerBannerPattern('snuzzle/text_illager/x', 'minecraft:pattern_item/thing', '""');
	registerBannerPattern('snuzzle/text_illager/y', 'minecraft:pattern_item/thing', '""');
	registerBannerPattern('snuzzle/text_illager/z', 'minecraft:pattern_item/thing', '""');
	registerBannerPattern('snuzzle/text_illager/comma', 'minecraft:pattern_item/thing', '""');
	registerBannerPattern('snuzzle/text_illager/exclamation', 'minecraft:pattern_item/thing', '""');
	registerBannerPattern('snuzzle/text_illager/period', 'minecraft:pattern_item/thing', '""');
	registerBannerPattern('snuzzle/text_illager/question', 'minecraft:pattern_item/thing', '""');
	registerBannerPattern('snuzzle/text_illager/0', 'minecraft:pattern_item/thing', '""');
	registerBannerPattern('snuzzle/text_illager/1', 'minecraft:pattern_item/thing', '""');
	registerBannerPattern('snuzzle/text_illager/2', 'minecraft:pattern_item/thing', '""');
	registerBannerPattern('snuzzle/text_illager/3', 'minecraft:pattern_item/thing', '""');
	registerBannerPattern('snuzzle/text_illager/4', 'minecraft:pattern_item/thing', '""');
	registerBannerPattern('snuzzle/text_illager/5', 'minecraft:pattern_item/thing', '""');
	registerBannerPattern('snuzzle/text_illager/6', 'minecraft:pattern_item/thing', '""');
	registerBannerPattern('snuzzle/text_illager/7', 'minecraft:pattern_item/thing', '""');
	registerBannerPattern('snuzzle/text_illager/8', 'minecraft:pattern_item/thing', '""');
	registerBannerPattern('snuzzle/text_illager/9', 'minecraft:pattern_item/thing', '""');
});
