StartupEvents.registry('enchantment', registry => {
	registry.create('radiance')
		.weapon()
		.veryRare()
		.treasureOnly()
		.minCost(level => { return 7 + 6 * (level - 1) })
		.maxCost(level => { return 8 + 6 * level })
		.maxLevel(4)

	registry.create('echo')
		.weapon()
		.rare()
		.minCost(level => { return 7 + 6 * (level - 1) })
		.maxCost(level => { return 14 + 6 * level })
		.maxLevel(5)

	registry.create('leeching')
		.weapon()
		.uncommon()
		.minCost(level => { return 10 + 5 * (level - 1) })
		.maxCost(level => { return 10 + 9 * level })
		.maxLevel(4)

	registry.create('prospector')
		.weapon()
		.veryRare()
		.treasureOnly()
		.minCost(level => { return 7 + 6 * (level - 1) })
		.maxCost(level => { return 8 + 6 * level })
		.maxLevel(4)

	registry.create('rampaging')
		.weapon()
		.veryRare()
		.minCost(level => { return 10 + 5 * (level - 1) })
		.maxCost(level => { return 16 + 6 * level })
		.maxLevel(4)

	registry.create('cowardice')
		.armorChest()
		.veryRare()
		.minCost(level => { return 10 + 5 * (level - 1) })
		.maxCost(level => { return 16 + 6 * level })
		.maxLevel(4)

	registry.create('lucky_explorer')
		.armorFeet()
		.treasureOnly()
		.untradeable()

	registry.create('reckless')
		.armorChest()
		.veryRare()
		.untradeable()
		.treasureOnly()
		.minCost(level => { return 10 + 5 * (level - 1) })
		.maxCost(level => { return 16 + 5 * level })
		.maxLevel(4)

	registry.create('rapid_regen')
		.armorChest()
		.rare()
		.treasureOnly()
		.minCost(level => { return 15 + 10 * (level - 1) })
		.maxCost(level => { return 16 + 13 * level })
		.maxLevel(4)

	registry.create('void_strike')
		.untradeable()
		.treasureOnly()
		.weapon()
		.curse()
		.minCost(level => { return 15 + 10 * (level - 1) })
		.maxCost(level => { return 16 + 13 * level })
		.maxLevel(3)

	registry.create('void_shot')
		.untradeable()
		.treasureOnly()
		.bow()
		.crossbow()
		.curse()
		.minCost(level => { return 15 + 10 * (level - 1) })
		.maxCost(level => { return 16 + 13 * level })
		.maxLevel(3)

	registry.create('committed')
		.weapon()
		.rare()
		.minCost(level => { return 7 + 6 * (level - 1) })
		.maxCost(level => { return 14 + 6 * level })
		.maxLevel(5)

	registry.create('curse_of_polarity')
		.weapon()
		.veryRare()
		.curse()
		.minCost(level => { return 20 })
		.maxCost(level => { return 50 })

	registry.create('curse_of_anti_entropy')
		.armor()
		.veryRare()
		.curse()
		.minCost(level => { return 20 })
		.maxCost(level => { return 50 })

	// registry.create('deferred_damage')
	// 	.armor()
	// 	.veryRare()
	// 	.curse()
	// 	.treasureOnly()
	// 	.minCost(level => { return 30 })
	// 	.maxCost(level => { return 50 })
})
