StartupEvents.registry('painting_variant', registry => {

	function registerPainting(id, width, height, name, author) {
		registry.create(id).height(height * 16).width(width * 16).tag('placeable');

		let base = `painting.kubejs.${id}`;
		global.addTranslation(`${base}.title`, name);
		global.addTranslation(`${base}.author`, global.getOrDefault('Unknown'));
	}

	registerPainting('dennis', 3, 3, 'Dennis', 'Sarah Boeving');
	registerPainting('pharaox', 2, 2, 'Humble Pharaoh');

	registerPainting('kohara/harlowville ', 2, 2, 'Scarlet Power', 'kohara');

	registerPainting('torrezx/amethyst_trim', 1, 1, 'Amethyst Trim', 'Torrezx');
	registerPainting('torrezx/camel_s', 1, 2, 'Camel S', 'Torrezx');
	registerPainting('torrezx/camel', 1, 1, 'Camel', 'Torrezx');
	registerPainting('torrezx/camels', 3, 2, 'Camels', 'Torrezx');
	registerPainting('torrezx/cherry_grove', 2, 1, 'Cherry Grove', 'Torrezx');
	registerPainting('torrezx/diamond_trim', 1, 1, 'Diamond Trim', 'Torrezx');
	registerPainting('torrezx/earth_chickens', 1, 1, 'Chickens', 'Torrezx');
	registerPainting('torrezx/earth_heart', 1, 1, 'Heart', 'Torrezx');
	registerPainting('torrezx/earth_melon', 1, 1, 'Melon', 'Torrezx');
	registerPainting('torrezx/earth_pig', 1, 1, 'Muddy Pig', 'Torrezx');
	registerPainting('torrezx/earth_rainbow', 1, 1, 'Rainbow', 'Torrezx');
	registerPainting('torrezx/earth_tropical_slime', 1, 1, 'Tropical Slime', 'Torrezx');
	registerPainting('torrezx/earth_wooly_cow', 1, 1, 'Wooly Cow', 'Torrezx');
	registerPainting('torrezx/emerald_trim', 1, 1, 'Emerald Trim', 'Torrezx');
	registerPainting('torrezx/gold_trim', 1, 1, 'Gold Trim', 'Torrezx');
	registerPainting('torrezx/netherite_trim', 1, 1, 'Netherite Trim', 'Torrezx');
	registerPainting('torrezx/redstone_trim', 1, 1, 'Redstone Trim', 'Torrezx');
	registerPainting('torrezx/sherd', 1, 1, 'Archaeology', 'Torrezx');
	registerPainting('torrezx/sniffer_egg', 2, 1, 'Repopulation', 'Torrezx');
	registerPainting('torrezx/sniffer', 2, 1, 'Endandgered Species', 'Torrezx');

	registerPainting('absolemjackdaw/abstract_blue', 1, 1, 'Abstract Blue', 'AbsolemJackdaw');
	registerPainting('absolemjackdaw/abstract_rainbow', 1, 1, 'Abstract Rainbow', 'AbsolemJackdaw');
	registerPainting('absolemjackdaw/abstract_red', 1, 1, 'Abstract Red', 'AbsolemJackdaw');
	registerPainting('absolemjackdaw/abstract_sunset', 1, 1, 'Abstract Sunset', 'AbsolemJackdaw');
	registerPainting('absolemjackdaw/arachnophobe', 2, 1, 'Arachnophobe', 'AbsolemJackdaw');
	registerPainting('absolemjackdaw/barn_owl', 2, 1, 'Barn Owl', 'AbsolemJackdaw');
	registerPainting('absolemjackdaw/big_z', 1, 1, 'Big Z', 'AbsolemJackdaw');
	registerPainting('absolemjackdaw/bluesclues', 2, 1, 'Bluesclues', 'AbsolemJackdaw');
	registerPainting('absolemjackdaw/blue_bird', 2, 1, 'Blue Bird', 'AbsolemJackdaw');
	registerPainting('absolemjackdaw/borgia', 1, 2, 'Borgia', 'AbsolemJackdaw');
	registerPainting('absolemjackdaw/cane', 1, 2, 'Cane', 'AbsolemJackdaw');
	registerPainting('absolemjackdaw/cat', 2, 1, 'Cat', 'AbsolemJackdaw');
	registerPainting('absolemjackdaw/cat_black', 1, 1, 'Cat Black', 'AbsolemJackdaw');
	registerPainting('absolemjackdaw/cat_gray', 1, 1, 'Cat Gray', 'AbsolemJackdaw');
	registerPainting('absolemjackdaw/cat_orange', 1, 1, 'Cat Orange', 'AbsolemJackdaw');
	registerPainting('absolemjackdaw/colorful_squares', 2, 1, 'Colorful Squares', 'AbsolemJackdaw');
	registerPainting('absolemjackdaw/crest', 2, 1, 'Crest', 'AbsolemJackdaw');
	registerPainting('absolemjackdaw/danger_zone', 2, 2, 'Danger Zone', 'AbsolemJackdaw');
	registerPainting('absolemjackdaw/decorative_gun', 2, 1, 'Decorative Gun', 'AbsolemJackdaw');
	registerPainting('absolemjackdaw/exit_down', 2, 1, 'Exit Down', 'AbsolemJackdaw');
	registerPainting('absolemjackdaw/exit_left', 2, 1, 'Exit Left', 'AbsolemJackdaw');
	registerPainting('absolemjackdaw/exit_right', 2, 1, 'Exit Right', 'AbsolemJackdaw');
	registerPainting('absolemjackdaw/exit_up', 2, 1, 'Exit Up', 'AbsolemJackdaw');
	registerPainting('absolemjackdaw/face_bat', 1, 1, 'Face Bat', 'AbsolemJackdaw');
	registerPainting('absolemjackdaw/face_chicken', 1, 1, 'Face Chicken', 'AbsolemJackdaw');
	registerPainting('absolemjackdaw/face_cow', 1, 1, 'Face Cow', 'AbsolemJackdaw');
	registerPainting('absolemjackdaw/face_creeper', 1, 1, 'Face Creeper', 'AbsolemJackdaw');
	registerPainting('absolemjackdaw/face_dog', 1, 1, 'Face Dog', 'AbsolemJackdaw');
	registerPainting('absolemjackdaw/face_enderman', 1, 1, 'Face Enderman', 'AbsolemJackdaw');
	registerPainting('absolemjackdaw/face_pig', 1, 1, 'Face Pig', 'AbsolemJackdaw');
	registerPainting('absolemjackdaw/face_pigman', 1, 1, 'Face Pigman', 'AbsolemJackdaw');
	registerPainting('absolemjackdaw/face_silverfish', 1, 1, 'Face Silverfish', 'AbsolemJackdaw');
	registerPainting('absolemjackdaw/face_skeleton', 1, 1, 'Face Skeleton', 'AbsolemJackdaw');
	registerPainting('absolemjackdaw/face_squid', 1, 1, 'Face Squid', 'AbsolemJackdaw');
	registerPainting('absolemjackdaw/face_steve', 1, 1, 'Face Steve', 'AbsolemJackdaw');
	registerPainting('absolemjackdaw/face_zombie', 1, 1, 'Face Zombie', 'AbsolemJackdaw');
	registerPainting('absolemjackdaw/fishes', 2, 1, 'Fishes', 'AbsolemJackdaw');
	registerPainting('absolemjackdaw/flowers', 2, 1, 'Flowers', 'AbsolemJackdaw');
	registerPainting('absolemjackdaw/fruits', 2, 1, 'Fruits', 'AbsolemJackdaw');
	registerPainting('absolemjackdaw/ghost', 1, 2, 'Ghost', 'AbsolemJackdaw');
	registerPainting('absolemjackdaw/glowlamp', 2, 2, 'Glowlamp', 'AbsolemJackdaw');
	registerPainting('absolemjackdaw/glowstone_hourglass', 1, 2, 'Glowstone Hourglass', 'AbsolemJackdaw');
	registerPainting('absolemjackdaw/iluvmc', 2, 1, 'Iluvmc', 'AbsolemJackdaw');
	registerPainting('absolemjackdaw/link', 2, 1, 'Link', 'AbsolemJackdaw');
	registerPainting('absolemjackdaw/mine_prosperity', 2, 1, 'Mine Prosperity', 'AbsolemJackdaw');
	registerPainting('absolemjackdaw/no_trespassing_for_mobs', 2, 1, 'No Trespassing For Mobs', 'AbsolemJackdaw');
	registerPainting('absolemjackdaw/ocelot', 1, 1, 'Ocelot', 'AbsolemJackdaw');
	registerPainting('absolemjackdaw/penguin', 2, 1, 'Penguin', 'AbsolemJackdaw');
	registerPainting('absolemjackdaw/pig_on_a_cliff', 2, 2, 'Pig On A Cliff', 'AbsolemJackdaw');
	registerPainting('absolemjackdaw/pkmn_blue', 2, 1, 'Pkmn Blue', 'AbsolemJackdaw');
	registerPainting('absolemjackdaw/pkmn_green', 2, 1, 'Pkmn Green', 'AbsolemJackdaw');
	registerPainting('absolemjackdaw/pkmn_red', 2, 1, 'Pkmn Red', 'AbsolemJackdaw');
	registerPainting('absolemjackdaw/plains_hut', 2, 1, 'Plains Hut', 'AbsolemJackdaw');
	registerPainting('absolemjackdaw/portrait', 1, 1, 'Portrait', 'AbsolemJackdaw');
	registerPainting('absolemjackdaw/portrait_2', 1, 1, 'Portrait 2', 'AbsolemJackdaw');
	registerPainting('absolemjackdaw/prison', 1, 2, 'Prison', 'AbsolemJackdaw');
	registerPainting('absolemjackdaw/prosperity', 1, 2, 'Prosperity', 'AbsolemJackdaw');
	registerPainting('absolemjackdaw/rest', 2, 1, 'Rest', 'AbsolemJackdaw');
	registerPainting('absolemjackdaw/skeleton', 1, 2, 'Skeleton', 'AbsolemJackdaw');
	registerPainting('absolemjackdaw/sky', 2, 2, 'Sky', 'AbsolemJackdaw');
	registerPainting('absolemjackdaw/skyblock', 2, 2, 'Skyblock', 'AbsolemJackdaw');
	registerPainting('absolemjackdaw/snake', 1, 2, 'Snake', 'AbsolemJackdaw');
	registerPainting('absolemjackdaw/snow_landscape', 2, 1, 'Snow Landscape', 'AbsolemJackdaw');
	registerPainting('absolemjackdaw/subaraki', 2, 1, 'Subaraki', 'AbsolemJackdaw');
	registerPainting('absolemjackdaw/synth_city', 1, 1, 'Synth City', 'AbsolemJackdaw');
	registerPainting('absolemjackdaw/tapistry_a', 2, 1, 'Tapistry A', 'AbsolemJackdaw');
	registerPainting('absolemjackdaw/tapistry_b', 1, 2, 'Tapistry B', 'AbsolemJackdaw');
	registerPainting('absolemjackdaw/tapistry_purple', 1, 2, 'Tapistry Purple', 'AbsolemJackdaw');
	registerPainting('absolemjackdaw/torched', 2, 1, 'Torched', 'AbsolemJackdaw');
	registerPainting('absolemjackdaw/waterfall', 2, 1, 'Waterfall', 'AbsolemJackdaw');
	registerPainting('absolemjackdaw/whale', 2, 1, 'Whale', 'AbsolemJackdaw');
	registerPainting('absolemjackdaw/wheat_field', 2, 1, 'Wheat Field', 'AbsolemJackdaw');
	registerPainting('absolemjackdaw/wolf_in_wheat', 2, 1, 'Wolf In Wheat', 'AbsolemJackdaw');

	registerPainting('dungeons/archillager_cool_guy', 2, 2, 'Arch-Illager is a Cool Guy', 'Mojang');
	registerPainting('dungeons/archillager_portrait', 2, 2, 'Arch-Illager', 'Mojang');
	registerPainting('dungeons/aunt', 3, 3, 'Aunt', 'Mojang');
	registerPainting('dungeons/banner', 3, 3, 'Banner', 'Mojang');
	registerPainting('dungeons/blue_fields', 1, 1, 'Blue Fields', 'Mojang');
	registerPainting('dungeons/bookshelf', 3, 3, 'Bookshelf', 'Mojang');
	registerPainting('dungeons/creeper', 1, 1, 'Creeper', 'Mojang');
	registerPainting('dungeons/creeper_ruins', 3, 2, 'Creeper Ruins', 'Mojang');
	registerPainting('dungeons/crocodile', 2, 2, 'Crocodile', 'Mojang');
	registerPainting('dungeons/desert_sunrise', 2, 4, 'Desert Sunrise', 'Mojang');
	registerPainting('dungeons/desert_temple', 3, 3, 'Desert Temple', 'Mojang');
	registerPainting('dungeons/evoker', 3, 3, 'Evoker', 'Mojang');
	registerPainting('dungeons/golden_dog', 3, 3, 'Golden Dog', 'Mojang');
	registerPainting('dungeons/golden_key', 3, 3, 'Golden Key', 'Mojang');
	registerPainting('dungeons/gravestone', 3, 3, 'Gravestone', 'Mojang');
	registerPainting('dungeons/lever', 3, 3, 'Lever', 'Mojang');
	registerPainting('dungeons/lighthouse', 3, 3, 'Lighthouse', 'Mojang');
	registerPainting('dungeons/light_in_the_cave', 3, 3, 'Light in The Cave', 'Mojang');
	registerPainting('dungeons/mountain', 2, 2, 'Mountain', 'Mojang');
	registerPainting('dungeons/mushrooms', 3, 3, 'Mushrooms', 'Mojang');
	registerPainting('dungeons/portal_in_the_dark', 2, 3, 'Portal in The Dark', 'Mojang');
	registerPainting('dungeons/redstone_crystals', 3, 3, 'Redstone Crystals', 'Mojang');
	registerPainting('dungeons/redstone_golem', 2, 1, 'Redstone Golem', 'Mojang');
	registerPainting('dungeons/shadow', 3, 3, 'Shadow', 'Mojang');
	registerPainting('dungeons/skeleton', 3, 3, 'Skeleton', 'Mojang');
	registerPainting('dungeons/tower ', 11, 16, 'Tower', 'Mojang');
	registerPainting('dungeons/tropical', 2, 2, 'Tropical', 'Mojang');
	registerPainting('dungeons/village_on_the_hill', 2, 2, 'Village on The Hill', 'Mojang');

	registerPainting('galacticspike/above_hells_roof', 2, 2, 'Above Hells Roof', 'GalacticSpike');
	registerPainting('galacticspike/afternoon_dance', 3, 2, 'Afternoon Dance', 'GalacticSpike');
	registerPainting('galacticspike/alien_landscapes', 4, 2, 'Alien Landscapes', 'GalacticSpike');
	registerPainting('galacticspike/alluring_allurestems', 2, 3, 'Alluring Allurestems', 'GalacticSpike');
	registerPainting('galacticspike/amidst_the_fields', 3, 4, 'Amidst The Fields', 'GalacticSpike');
	registerPainting('galacticspike/ancestral_collumn', 3, 3, 'Ancestral Collumn', 'GalacticSpike');
	registerPainting('galacticspike/angel_in_the_frame', 1, 2, 'Angel In The Frame', 'GalacticSpike');
	registerPainting('galacticspike/an_evening_lightshow', 4, 2, 'An Evening Lightshow', 'GalacticSpike');
	registerPainting('galacticspike/arbor_ex_somniis_nata', 2, 3, 'Arbor Ex Somniis Nata', 'GalacticSpike');
	registerPainting('galacticspike/aspect_of_war', 2, 3, 'Aspect Of War', 'GalacticSpike');
	registerPainting('galacticspike/autumn_streets', 3, 3, 'Autumn Streets', 'GalacticSpike');
	registerPainting('galacticspike/barren_rock_allure', 4, 2, 'Barren Rock Allure', 'GalacticSpike');
	registerPainting('galacticspike/beached_anchor', 2, 1, 'Beached Anchor', 'GalacticSpike');
	registerPainting('galacticspike/beach_date', 2, 2, 'Beach Date', 'GalacticSpike');
	registerPainting('galacticspike/beyond_a_distant_nebula', 3, 3, 'Beyond A Distant Nebula', 'GalacticSpike');
	registerPainting('galacticspike/binary_man', 2, 2, 'Binary Man', 'GalacticSpike');
	registerPainting('galacticspike/bioluminescent_beauty', 1, 2, 'Bioluminescent Beauty', 'GalacticSpike');
	registerPainting('galacticspike/blood_moon', 2, 2, 'Blood Moon', 'GalacticSpike');
	registerPainting('galacticspike/blooming_chorus_field', 2, 3, 'Blooming Chorus Field', 'GalacticSpike');
	registerPainting('galacticspike/blossoming_chorusbloom', 1, 2, 'Blossoming Chorusbloom', 'GalacticSpike');
	registerPainting('galacticspike/boreal_metropolis', 1, 2, 'Boreal Metropolis', 'GalacticSpike');
	registerPainting('galacticspike/brutish_portrait', 2, 2, 'Brutish Portrait', 'GalacticSpike');
	registerPainting('galacticspike/bubbles_and_spikes', 1, 2, 'Bubbles And Spikes', 'GalacticSpike');
	registerPainting('galacticspike/cackling_from_the_garden', 2, 2, 'Cackling From The Garden', 'GalacticSpike');
	registerPainting('galacticspike/calming_beach', 1, 1, 'Calming Beach', 'GalacticSpike');
	registerPainting('galacticspike/celestial_sights', 1, 2, 'Celestial Sights', 'GalacticSpike');
	registerPainting('galacticspike/challenging_the_storm', 3, 2, 'Challenging The Storm', 'GalacticSpike');
	registerPainting('galacticspike/changing_of_the_season', 2, 1, 'Changing Of The Season', 'GalacticSpike');
	registerPainting('galacticspike/classic_fruit_bowl', 2, 2, 'Classic Fruit Bowl', 'GalacticSpike');
	registerPainting('galacticspike/collision_course', 2, 1, 'Collision Course', 'GalacticSpike');
	registerPainting('galacticspike/cozy_bay', 3, 2, 'Cozy Bay', 'GalacticSpike');
	registerPainting('galacticspike/cross_gaze', 2, 3, 'Cross Gaze', 'GalacticSpike');
	registerPainting('galacticspike/dark_manor', 2, 2, 'Dark Manor', 'GalacticSpike');
	registerPainting('galacticspike/dearest_home', 1, 2, 'Dearest Home', 'GalacticSpike');
	registerPainting('galacticspike/delicate_features', 1, 2, 'Delicate Features', 'GalacticSpike');
	registerPainting('galacticspike/distant_paradise', 4, 2, 'Distant Paradise', 'GalacticSpike');
	registerPainting('galacticspike/distant_rings', 1, 1, 'Distant Rings', 'GalacticSpike');
	registerPainting('galacticspike/down_by_the_river', 2, 1, 'Down By The River', 'GalacticSpike');
	registerPainting('galacticspike/eastern_vistas', 3, 3, 'Eastern Vistas', 'GalacticSpike');
	registerPainting('galacticspike/eclipsed', 2, 2, 'Eclipsed', 'GalacticSpike');
	registerPainting('galacticspike/eeriest_halls', 2, 2, 'Eeriest Halls', 'GalacticSpike');
	registerPainting('galacticspike/eerie_visage', 1, 2, 'Eerie Visage', 'GalacticSpike');
	registerPainting('galacticspike/end_static', 3, 3, 'End Static', 'GalacticSpike');
	registerPainting('galacticspike/enigmatic_visitor', 2, 1, 'Enigmatic Visitor', 'GalacticSpike');
	registerPainting('galacticspike/etheric_ripples', 3, 3, 'Etheric Ripples', 'GalacticSpike');
	registerPainting('galacticspike/evoking_emotions', 2, 2, 'Evoking Emotions', 'GalacticSpike');
	registerPainting('galacticspike/exotic_petals', 2, 3, 'Exotic Petals', 'GalacticSpike');
	registerPainting('galacticspike/eyes_amongst_the_trees', 1, 2, 'Eyes Amongst The Trees', 'GalacticSpike');
	registerPainting('galacticspike/fable_of_the_white_pumpkin', 2, 2, 'Fable Of The White Pumpkin', 'GalacticSpike');
	registerPainting('galacticspike/faces_and_shapes', 1, 1, 'Faces And Shapes', 'GalacticSpike');
	registerPainting('galacticspike/fairy_garden', 1, 2, 'Fairy Garden', 'GalacticSpike');
	registerPainting('galacticspike/fall_comes_for_the_ruins', 4, 2, 'Fall Comes For The Ruins', 'GalacticSpike');
	registerPainting('galacticspike/familiarity_in_the_alien', 4, 2, 'Familiarity In The Alien', 'GalacticSpike');
	registerPainting('galacticspike/familiar_face', 1, 1, 'Familiar Face', 'GalacticSpike');
	registerPainting('galacticspike/far_away_lands', 1, 1, 'Far Away Lands', 'GalacticSpike');
	registerPainting('galacticspike/fiery_demise', 2, 1, 'Fiery Demise', 'GalacticSpike');
	registerPainting('galacticspike/final_frontier', 3, 3, 'Final Frontier', 'GalacticSpike');
	registerPainting('galacticspike/floral_omens', 1, 1, 'Floral Omens', 'GalacticSpike');
	registerPainting('galacticspike/flowering_warps', 1, 2, 'Flowering Warps', 'GalacticSpike');
	registerPainting('galacticspike/flower_of_the_wild', 2, 3, 'Flower Of The Wild', 'GalacticSpike');
	registerPainting('galacticspike/forever_watching', 2, 4, 'Forever Watching', 'GalacticSpike');
	registerPainting('galacticspike/frozen_bones', 3, 2, 'Frozen Bones', 'GalacticSpike');
	registerPainting('galacticspike/full_moon', 2, 2, 'Full Moon', 'GalacticSpike');
	registerPainting('galacticspike/glowing_ribcage', 2, 2, 'Glowing Ribcage', 'GalacticSpike');
	registerPainting('galacticspike/going_under', 1, 1, 'Going Under', 'GalacticSpike');
	registerPainting('galacticspike/grave_on_the_hill', 2, 2, 'Grave On The Hill', 'GalacticSpike');
	registerPainting('galacticspike/grayscale_world', 1, 1, 'Grayscale World', 'GalacticSpike');
	registerPainting('galacticspike/guiding_light', 2, 1, 'Guiding Light', 'GalacticSpike');
	registerPainting('galacticspike/halo_over_glass', 1, 1, 'Halo Over Glass', 'GalacticSpike');
	registerPainting('galacticspike/haunting_visage', 2, 2, 'Haunting Visage', 'GalacticSpike');
	registerPainting('galacticspike/heavy_is_the_crown', 1, 1, 'Heavy Is The Crown', 'GalacticSpike');
	registerPainting('galacticspike/house_away_from_sol', 3, 2, 'House Away From Sol', 'GalacticSpike');
	registerPainting('galacticspike/icy_monolith', 2, 1, 'Icy Monolith', 'GalacticSpike');
	registerPainting('galacticspike/inventors_lair', 2, 3, 'Inventors Lair', 'GalacticSpike');
	registerPainting('galacticspike/in_the_aftermath', 3, 4, 'In The Aftermath', 'GalacticSpike');
	registerPainting('galacticspike/in_the_heart_of_the_savanna', 3, 2, 'In The Heart Of The Savanna', 'GalacticSpike');
	registerPainting('galacticspike/in_the_murky_deep', 2, 2, 'In The Murky Deep', 'GalacticSpike');
	registerPainting('galacticspike/islands_in_the_sky', 2, 3, 'Islands In The Sky', 'GalacticSpike');
	registerPainting('galacticspike/jovian_clouds', 3, 3, 'Jovian Clouds', 'GalacticSpike');
	registerPainting('galacticspike/lady_of_the_manor', 3, 4, 'Lady Of The Manor', 'GalacticSpike');
	registerPainting('galacticspike/laughing_pumpkins', 1, 2, 'Laughing Pumpkins', 'GalacticSpike');
	registerPainting('galacticspike/legends_and_crystals', 2, 2, 'Legends And Crystals', 'GalacticSpike');
	registerPainting('galacticspike/life_in_the_sky', 2, 2, 'Life In The Sky', 'GalacticSpike');
	registerPainting('galacticspike/light_after_the_fight', 1, 2, 'Light After The Fight', 'GalacticSpike');
	registerPainting('galacticspike/lively_canopy', 3, 3, 'Lively Canopy', 'GalacticSpike');
	registerPainting('galacticspike/lonely_light', 2, 2, 'Lonely Light', 'GalacticSpike');
	registerPainting('galacticspike/lonely_tree', 3, 3, 'Lonely Tree', 'GalacticSpike');
	registerPainting('galacticspike/lone_twisted_tree', 1, 2, 'Lone Twisted Tree', 'GalacticSpike');
	registerPainting('galacticspike/looming_dragon', 2, 3, 'Looming Dragon', 'GalacticSpike');
	registerPainting('galacticspike/lost_to_nature', 2, 2, 'Lost To Nature', 'GalacticSpike');
	registerPainting('galacticspike/magma_flow', 2, 1, 'Magma Flow', 'GalacticSpike');
	registerPainting('galacticspike/mansion_in_the_woods', 2, 2, 'Mansion In The Woods', 'GalacticSpike');
	registerPainting('galacticspike/master_of_the_craft', 2, 2, 'Master Of The Craft', 'GalacticSpike');
	registerPainting('galacticspike/menacing_portrait', 2, 2, 'Menacing Portrait', 'GalacticSpike');
	registerPainting('galacticspike/monster_of_the_night_skies', 3, 2, 'Monster Of The Night Skies', 'GalacticSpike');
	registerPainting('galacticspike/mystical_allurestem', 1, 2, 'Mystical Allurestem', 'GalacticSpike');
	registerPainting('galacticspike/mystic_essences', 1, 2, 'Mystic Essences', 'GalacticSpike');
	registerPainting('galacticspike/nameless_girl', 1, 1, 'Nameless Girl', 'GalacticSpike');
	registerPainting('galacticspike/never_returning', 3, 3, 'Never Returning', 'GalacticSpike');
	registerPainting('galacticspike/new_adventure', 1, 2, 'New Adventure', 'GalacticSpike');
	registerPainting('galacticspike/old_giant', 1, 2, 'Old Giant', 'GalacticSpike');
	registerPainting('galacticspike/old_road', 4, 2, 'Old Road', 'GalacticSpike');
	registerPainting('galacticspike/peaceful_night', 2, 3, 'Peaceful Night', 'GalacticSpike');
	registerPainting('galacticspike/planter_pot_horizon', 2, 3, 'Planter Pot Horizon', 'GalacticSpike');
	registerPainting('galacticspike/plush_of_doom', 3, 3, 'Plush Of Doom', 'GalacticSpike');
	registerPainting('galacticspike/prehistoric_goop', 2, 1, 'Prehistoric Goop', 'GalacticSpike');
	registerPainting('galacticspike/primal_beauty', 1, 2, 'Primal Beauty', 'GalacticSpike');
	registerPainting('galacticspike/psychadelia', 2, 3, 'Psychadelia', 'GalacticSpike');
	registerPainting('galacticspike/reaching_from_the_deep', 2, 1, 'Reaching From The Deep', 'GalacticSpike');
	registerPainting('galacticspike/red_zeppelin', 2, 1, 'Red Zeppelin', 'GalacticSpike');
	registerPainting('galacticspike/remnant_on_rock', 1, 1, 'Remnant On Rock', 'GalacticSpike');
	registerPainting('galacticspike/restaurant_scenery', 3, 2, 'Restaurant Scenery', 'GalacticSpike');
	registerPainting('galacticspike/rising_kelp', 1, 2, 'Rising Kelp', 'GalacticSpike');
	registerPainting('galacticspike/rough_seas', 2, 3, 'Rough Seas', 'GalacticSpike');
	registerPainting('galacticspike/rune_stone', 2, 2, 'Rune Stone', 'GalacticSpike');
	registerPainting('galacticspike/salt_and_flowers', 1, 2, 'Salt And Flowers', 'GalacticSpike');
	registerPainting('galacticspike/sandy_monolith', 4, 2, 'Sandy Monolith', 'GalacticSpike');
	registerPainting('galacticspike/scarlettine_workshop', 2, 2, 'Scarlettine Workshop', 'GalacticSpike');
	registerPainting('galacticspike/scenic_mountain_range', 3, 2, 'Scenic Mountain Range', 'GalacticSpike');
	registerPainting('galacticspike/scopaesthesia', 2, 3, 'Scopaesthesia', 'GalacticSpike');
	registerPainting('galacticspike/scorching_heat', 2, 2, 'Scorching Heat', 'GalacticSpike');
	registerPainting('galacticspike/serenity_and_hot_water', 1, 2, 'Serenity And Hot Water', 'GalacticSpike');
	registerPainting('galacticspike/shark_waters', 3, 3, 'Shark Waters', 'GalacticSpike');
	registerPainting('galacticspike/shiny_rocks', 2, 1, 'Shiny Rocks', 'GalacticSpike');
	registerPainting('galacticspike/signs_of_change', 1, 1, 'Signs Of Change', 'GalacticSpike');
	registerPainting('galacticspike/silence_and_fear', 3, 2, 'Silence And Fear', 'GalacticSpike');
	registerPainting('galacticspike/skeletons_cards', 1, 2, 'Skeletons Cards', 'GalacticSpike');
	registerPainting('galacticspike/snow_and_solitude', 3, 3, 'Snow And Solitude', 'GalacticSpike');
	registerPainting('galacticspike/something_in_the_void', 2, 2, 'Something In The Void', 'GalacticSpike');
	registerPainting('galacticspike/somewhere_up_north', 1, 2, 'Somewhere Up North', 'GalacticSpike');
	registerPainting('galacticspike/special_egg', 1, 1, 'Special Egg', 'GalacticSpike');
	registerPainting('galacticspike/spiralling_puffs', 3, 3, 'Spiralling Puffs', 'GalacticSpike');
	registerPainting('galacticspike/starry_barrens', 3, 2, 'Starry Barrens', 'GalacticSpike');
	registerPainting('galacticspike/struggle_for_dominance', 2, 3, 'Struggle For Dominance', 'GalacticSpike');
	registerPainting('galacticspike/sulphuric_hollows', 4, 2, 'Sulphuric Hollows', 'GalacticSpike');
	registerPainting('galacticspike/sunny_cove_blossom', 2, 3, 'Sunny Cove Blossom', 'GalacticSpike');
	registerPainting('galacticspike/sunset_at_sea', 2, 1, 'Sunset At Sea', 'GalacticSpike');
	registerPainting('galacticspike/synth_dreams', 1, 2, 'Synth Dreams', 'GalacticSpike');
	registerPainting('galacticspike/the_formless_stare', 1, 1, 'The Formless Stare', 'GalacticSpike');
	registerPainting('galacticspike/the_glare', 1, 2, 'The Glare', 'GalacticSpike');
	registerPainting('galacticspike/the_shroom', 3, 3, 'The Shroom', 'GalacticSpike');
	registerPainting('galacticspike/the_wanderer', 2, 2, 'The Wanderer', 'GalacticSpike');
	registerPainting('galacticspike/tornado_season', 2, 1, 'Tornado Season', 'GalacticSpike');
	registerPainting('galacticspike/torn_memory', 3, 3, 'Torn Memory', 'GalacticSpike');
	registerPainting('galacticspike/toxic_world', 2, 1, 'Toxic World', 'GalacticSpike');
	registerPainting('galacticspike/treehouse_living', 3, 4, 'Treehouse Living', 'GalacticSpike');
	registerPainting('galacticspike/tree_of_serenity', 4, 3, 'Tree Of Serenity', 'GalacticSpike');
	registerPainting('galacticspike/vibrant_jungle_life', 3, 2, 'Vibrant Jungle Life', 'GalacticSpike');
	registerPainting('galacticspike/warped_petals', 2, 3, 'Warped Petals', 'GalacticSpike');
	registerPainting('galacticspike/weeping_by_the_river', 4, 2, 'Weeping By The River', 'GalacticSpike');
	registerPainting('galacticspike/wet_pastures', 2, 2, 'Wet Pastures', 'GalacticSpike');
	registerPainting('galacticspike/witches_take_flight', 4, 4, 'Witches Take Flight', 'GalacticSpike');
	registerPainting('galacticspike/wizards_tower', 1, 2, 'Wizards Tower', 'GalacticSpike');
	registerPainting('galacticspike/woodpecker_bird', 2, 3, 'Woodpecker Bird', 'GalacticSpike');
	registerPainting('galacticspike/workshop_accident', 2, 2, 'Workshop Accident', 'GalacticSpike');

	registerPainting('mangocraft/harlowville ', 4, 3, 'Harlowville', 'FokaStudio');

	registerPainting('nicxd/badlands', 1, 1, 'Badlands', 'nicxd');
	registerPainting('nicxd/badlands_sunrise', 2, 2, 'Badlands Sunrise', 'nicxd');
	registerPainting('nicxd/badlands_sunset', 4, 2, 'Badlands Sunset', 'nicxd');
	registerPainting('nicxd/beacon', 4, 2, 'Beacon', 'nicxd');
	registerPainting('nicxd/bunny', 1, 2, 'Bunny', 'nicxd');
	registerPainting('nicxd/cat', 1, 1, 'Cat', 'nicxd');
	registerPainting('nicxd/chicken', 3, 4, 'Chicken', 'nicxd');
	registerPainting('nicxd/creeper', 1, 1, 'Creeper', 'nicxd');
	registerPainting('nicxd/desert_pyramid', 2, 1, 'Desert Pyramid', 'nicxd');
	registerPainting('nicxd/diamonds', 3, 3, 'Diamonds', 'nicxd');
	registerPainting('nicxd/enchanter', 3, 3, 'Enchanter', 'nicxd');
	registerPainting('nicxd/evoker', 4, 4, 'Evoker', 'nicxd');
	registerPainting('nicxd/fortress', 3, 3, 'Fortress', 'nicxd');
	registerPainting('nicxd/goat', 3, 3, 'Goat', 'nicxd');
	registerPainting('nicxd/grove', 2, 1, 'Grove', 'nicxd');
	registerPainting('nicxd/hell', 2, 2, 'Hell', 'nicxd');
	registerPainting('nicxd/hmm', 2, 2, 'Hmm', 'nicxd');
	registerPainting('nicxd/mansion', 3, 3, 'Mansion', 'nicxd');
	registerPainting('nicxd/mineshaft', 3, 3, 'Mineshaft', 'nicxd');
	registerPainting('nicxd/modrian', 2, 1, 'Modrian', 'nicxd');
	registerPainting('nicxd/moon', 1, 1, 'Moon', 'nicxd');
	registerPainting('nicxd/mountaintops', 1, 1, 'Mountaintops', 'nicxd');
	registerPainting('nicxd/mushroom_island', 3, 3, 'Mushroom Island', 'nicxd');
	registerPainting('nicxd/nether', 1, 2, 'Nether', 'nicxd');
	registerPainting('nicxd/outpost', 2, 2, 'Outpost', 'nicxd');
	registerPainting('nicxd/penguins', 4, 4, 'Penguins', 'nicxd');
	registerPainting('nicxd/portal', 4, 2, 'Portal', 'nicxd');
	registerPainting('nicxd/relic', 4, 4, 'Relic', 'nicxd');
	registerPainting('nicxd/river', 4, 3, 'River', 'nicxd');
	registerPainting('nicxd/steve', 2, 2, 'Steve', 'nicxd');
	registerPainting('nicxd/sweet_home', 2, 1, 'Sweet Home', 'nicxd');
	registerPainting('nicxd/taiga_sunrise', 2, 2, 'Taiga Sunrise', 'nicxd');
	registerPainting('nicxd/taiga_sunset', 2, 1, 'Taiga Sunset', 'nicxd');
	registerPainting('nicxd/to_the_end', 4, 2, 'To The End', 'nicxd');
	registerPainting('nicxd/underwater', 1, 1, 'Underwater', 'nicxd');
	registerPainting('nicxd/warden', 4, 2, 'Warden', 'nicxd');
	registerPainting('nicxd/wasteland', 1, 1, 'Wasteland', 'nicxd');
	registerPainting('nicxd/wololo', 3, 3, 'Wololo', 'nicxd');
	registerPainting('podagra/cake', 2, 2, 'Cake', 'podagra');
	registerPainting('podagra/copper', 1, 1, 'Copper', 'podagra');
	registerPainting('podagra/crafting', 1, 3, 'Crafting', 'podagra');
	registerPainting('podagra/discontinued', 2, 3, 'Discontinued', 'podagra');
	registerPainting('podagra/fire', 2, 2, 'Fire', 'podagra');
	registerPainting('podagra/gloom', 2, 2, 'Gloom', 'podagra');
	registerPainting('podagra/lighting', 1, 3, 'Lighting', 'podagra');
	registerPainting('podagra/mansion', 3, 2, 'Mansion', 'podagra');
	registerPainting('podagra/night', 1, 1, 'Night', 'podagra');
	registerPainting('podagra/palette', 2, 2, 'Palette', 'podagra');
	registerPainting('podagra/plains', 2, 2, 'Plains', 'podagra');
	registerPainting('podagra/punishment', 3, 1, 'Punishment', 'podagra');
	registerPainting('podagra/sky', 4, 2, 'Sky', 'podagra');
	registerPainting('podagra/throne', 3, 3, 'Throne', 'podagra');
	registerPainting('podagra/tiltedscale', 1, 1, 'Tiltedscale', 'podagra');
	registerPainting('podagra/tomorrow', 2, 2, 'Tomorrow', 'podagra');
	registerPainting('podagra/trident', 3, 1, 'Trident', 'podagra');

	registerPainting('potato/abstractato', 2, 2, 'Tasty Shapes', 'Mr. Potato');
	registerPainting('potato/burning_potato', 4, 4, 'Hot Potato', 'Mr. Potato');
	registerPainting('potato/ceci', 8, 4, 'This is not a potato', 'Mr. Potato');
	registerPainting('potato/mr_potato', 2, 3, 'Self Portrait ', 'Mr. Potato');
	registerPainting('potato/poisonous_potato', 8, 8, 'The Treachery of Potatoes', 'Mr. Potato');
	registerPainting('potato/potatoe', 4, 2, 'Potato', 'Mr. Potato');
	registerPainting('potato/ubiquitato', 3, 3, 'In The Spotlight', 'Mr. Potato');
	
	registerPainting('slimesmc/accident', 1, 1, 'Accident', 'Slimesmc');
	registerPainting('slimesmc/afternoon', 1, 3, 'Afternoon', 'Slimesmc');
	registerPainting('slimesmc/alpha', 2, 2, 'Alpha', 'Slimesmc');
	registerPainting('slimesmc/and_the_universe_said_i_love_you', 2, 3, 'And The Universe Said I Love You', 'Slimesmc');
	registerPainting('slimesmc/brick_monster', 3, 1, 'Brick Monster', 'Slimesmc');
	registerPainting('slimesmc/creepy', 3, 2, 'Creepy', 'Slimesmc');
	registerPainting('slimesmc/cult', 2, 3, 'Cult', 'Slimesmc');
	registerPainting('slimesmc/ending', 3, 2, 'Ending', 'Slimesmc');
	registerPainting('slimesmc/euphoria', 1, 1, 'Euphoria', 'Slimesmc');
	registerPainting('slimesmc/eyes', 2, 1, 'Eyes', 'Slimesmc');
	registerPainting('slimesmc/fights_on_the_underwater_heights', 2, 2, 'Fights On The Underwater Heights', 'Slimesmc');
	registerPainting('slimesmc/final_bloom', 1, 3, 'Final Bloom', 'Slimesmc');
	registerPainting('slimesmc/flowers', 1, 2, 'Flowers', 'Slimesmc');
	registerPainting('slimesmc/guardian_angel', 1, 1, 'Guardian Angel', 'Slimesmc');
	registerPainting('slimesmc/heartcore', 2, 3, 'Heartcore', 'Slimesmc');
	registerPainting('slimesmc/inbetweenlands', 4, 2, 'Inbetweenlands', 'Slimesmc');
	registerPainting('slimesmc/kitty', 3, 6, 'Kitty', 'Slimesmc');
	registerPainting('slimesmc/lotl', 2, 2, 'Lotl', 'Slimesmc');
	registerPainting('slimesmc/meaningless', 1, 2, 'Meaningless', 'Slimesmc');
	registerPainting('slimesmc/mourned_demise', 2, 3, 'Mourned Demise', 'Slimesmc');
	registerPainting('slimesmc/mouse_on_venus', 1, 1, 'Mouse On Venus', 'Slimesmc');
	registerPainting('slimesmc/ocean', 2, 3, 'Ocean', 'Slimesmc');
	registerPainting('slimesmc/painting', 1, 2, 'Painting', 'Slimesmc');
	registerPainting('slimesmc/pillars', 1, 3, 'Pillars', 'Slimesmc');
	registerPainting('slimesmc/pools', 2, 3, 'Pools', 'Slimesmc');
	registerPainting('slimesmc/screaming', 3, 1, 'Screaming', 'Slimesmc');
	registerPainting('slimesmc/self_reflection', 1, 2, 'Self Reflection', 'Slimesmc');
	registerPainting('slimesmc/shattered_dream', 2, 3, 'Shattered Dream', 'Slimesmc');
	registerPainting('slimesmc/slimy', 3, 3, 'Slimy', 'Slimesmc');
	registerPainting('slimesmc/stare', 1, 2, 'Stare', 'Slimesmc');
	registerPainting('slimesmc/taiga', 2, 3, 'Taiga', 'Slimesmc');
	registerPainting('slimesmc/the_sun_has_set', 2, 1, 'The Sun Has Set', 'Slimesmc');
	registerPainting('slimesmc/the_tree_of_life', 6, 4, 'The Tree Of Life', 'Slimesmc');
	registerPainting('slimesmc/time_flies', 2, 3, 'Time Flies', 'Slimesmc');
	registerPainting('slimesmc/tropical_fih', 2, 2, 'Tropical Fih', 'Slimesmc');
	registerPainting('slimesmc/underwater', 1, 3, 'Underwater', 'Slimesmc');
	registerPainting('slimesmc/warden_of_the_bloodmoon', 2, 3, 'Warden Of The Bloodmoon', 'Slimesmc');
	registerPainting('slimesmc/wardona_lisa', 2, 3, 'Wardona Lisa', 'Slimesmc');
	registerPainting('slimesmc/watching', 2, 2, 'Watching', 'Slimesmc');
	registerPainting('slimesmc/waves', 2, 2, 'Waves', 'Slimesmc');
	registerPainting('slimesmc/winter_wonderland', 2, 2, 'Winter Wonderland', 'Slimesmc');
	registerPainting('slimesmc/yondering_cranium', 3, 3, 'Yondering Cranium', 'Slimesmc');
	registerPainting('slimesmc/you_have_been_trolled', 3, 1, 'You Have Been Trolled', 'Slimesmc');

});
