#DKS mod relies on the existence of the options.txt file to detect whether it is a fresh
#startup of the game. But mods like Default Options will generate this file at the very
#beginning of the game startup, which makes this approach infeasible. So this option was
#introduced to force the key binding reset on next startup.
force_key_reset = true
#Current default setup for key bindings. It will be applied if option.txt does not exist.
#DO NOT TRY TO MODIFY THIS MANUALLY! USE THE CONFIG GUI IN GAME INSTEAD!
default_key_setup = [
	"key.attack=key.mouse.left:NONE",
	"key.use=key.mouse.right:NONE",
	"key.forward=key.keyboard.w:NONE",
	"key.left=key.keyboard.a:NONE",
	"key.back=key.keyboard.s:NONE",
	"key.right=key.keyboard.d:NONE",
	"key.jump=key.keyboard.space:NONE",
	"key.sneak=key.keyboard.left.shift:NONE",
	"key.sprint=key.keyboard.left.control:NONE",
	"key.drop=key.keyboard.q:NONE",
	"key.inventory=key.keyboard.e:NONE",
	"key.chat=key.keyboard.t:NONE",
	"key.playerlist=key.keyboard.tab:NONE",
	"key.pickItem=key.mouse.middle:NONE",
	"key.command=key.keyboard.slash:NONE",
	"key.socialInteractions=key.keyboard.p:NONE",
	"key.screenshot=key.keyboard.f4:NONE",
	"key.togglePerspective=key.keyboard.f5:NONE",
	"key.fullscreen=key.keyboard.f11:NONE",
	"key.swapOffhand=key.keyboard.f:NONE",
	"key.saveToolbarActivator=key.keyboard.c:NONE",
	"key.loadToolbarActivator=key.keyboard.x:NONE",
	"key.hotbar.1=key.keyboard.1:NONE",
	"key.hotbar.2=key.keyboard.2:NONE",
	"key.hotbar.3=key.keyboard.3:NONE",
	"key.hotbar.4=key.keyboard.4:NONE",
	"key.hotbar.5=key.keyboard.5:NONE",
	"key.hotbar.6=key.keyboard.6:NONE",
	"key.hotbar.7=key.keyboard.7:NONE",
	"key.hotbar.8=key.keyboard.8:NONE",
	"key.hotbar.9=key.keyboard.9:NONE",
	"key.firstperson.toggle=key.keyboard.f6:NONE",
	"info.structure_gel.building_tool.undo=key.keyboard.z:CONTROL",
	"info.structure_gel.building_tool.redo=key.keyboard.y:CONTROL",
	"key.structure_gel.open_building_tool_gui=key.keyboard.r:NONE",
	"key.botania_corporea_request=key.keyboard.c:NONE",
	"iris.keybind.reload=key.keyboard.unknown:NONE",
	"iris.keybind.toggleShaders=key.keyboard.unknown:NONE",
	"iris.keybind.shaderPackSelection=key.keyboard.unknown:NONE",
	"key.the_bumblezone.beehemoth_up=key.keyboard.space:NONE",
	"key.the_bumblezone.beehemoth_down=key.keyboard.caps.lock:NONE",
	"key.toms_storage.open_terminal=key.keyboard.e:CONTROL",
	"key.confluence.metal_detector=key.keyboard.right.control:NONE",
	"key.confluence.step_stool=key.keyboard.up:NONE",
	"key.scholar.toggle_book_tools=key.keyboard.unknown:NONE",
	"key.scholar.import_book=key.keyboard.unknown:NONE",
	"key.scholar.export_book=key.keyboard.unknown:NONE",
	"key.push_to_talk=key.keyboard.unknown:NONE",
	"key.whisper=key.keyboard.unknown:NONE",
	"key.mute_microphone=key.keyboard.m:NONE",
	"key.voice_chat=key.keyboard.v:NONE",
	"key.voice_chat_settings=key.keyboard.unknown:NONE",
	"key.shouldersurfing.adjust_camera_left=key.keyboard.left:CONTROL",
	"key.shouldersurfing.adjust_camera_right=key.keyboard.right:CONTROL",
	"key.shouldersurfing.adjust_camera_in=key.keyboard.up:CONTROL",
	"key.shouldersurfing.adjust_camera_out=key.keyboard.down:CONTROL",
	"key.shouldersurfing.adjust_camera_up=key.keyboard.page.up:CONTROL",
	"key.shouldersurfing.adjust_camera_down=key.keyboard.page.up:CONTROL",
	"key.shouldersurfing.swap_shoulder=key.keyboard.f7:NONE",
	"key.shouldersurfing.free_look=key.keyboard.left.alt:NONE",
	"placebo.toggleTrails=key.keyboard.keypad.9:NONE",
	"placebo.toggleWings=key.keyboard.keypad.8:NONE",
	"key.carry.desc=key.keyboard.left.shift:NONE",
	"key.cataclysm.ability=key.keyboard.x:NONE",
	"key.cataclysm.helmet_ability=key.keyboard.c:NONE",
	"key.cataclysm.chestplate_ability=key.keyboard.y:NONE",
	"key.cataclysm.boots_ability=key.keyboard.v:NONE",
	"key.spyglass-improvements.use=key.keyboard.z:NONE",
	"key.backpack=key.keyboard.b:NONE",
	"key.showmeyourskin.open_settings=key.keyboard.unknown:NONE",
	"terrastorage.keybinding.favorite_item_modifier=key.keyboard.left.alt:NONE",
	"key.map_atlases.open_minimap=key.keyboard.unknown:NONE",
	"key.map_atlases.zoom_out_minimap=key.keyboard.keypad.subtract:NONE",
	"key.map_atlases.zoom_in_minimap=key.keyboard.keypad.add:NONE",
	"ponder.keyinfo.ponder=key.keyboard.w:NONE",
	"keybinds.combatroll.roll=key.keyboard.r:NONE",
	"key.open_menu=key.keyboard.m:NONE",
	"key.ars_nouveau.open_book=key.keyboard.c:NONE",
	"key.ars_nouveau.selection_hud=key.mouse.middle:NONE",
	"key.ars_nouveau.next_slot=key.keyboard.right:NONE",
	"key.ars_nouveau.previous_slot=key.keyboard.left:NONE",
	"key.ars_nouveau.head_curio_hotkey=key.keyboard.g:NONE",
	"key.ars_elemental.open_pouch=key.keyboard.j:NONE",
	"key.aether.open_accessories.desc=key.keyboard.unknown:NONE",
	"key.aether.gravitite_jump_ability.desc=key.keyboard.space:NONE",
	"key.aether.invisibility_toggle.desc=key.keyboard.v:NONE",
	"key.aether_redux.shoot_fireball.desc=key.keyboard.h:NONE",
	"adjcore.loadout.1=key.keyboard.f1:NONE",
	"adjcore.loadout.2=key.keyboard.f2:NONE",
	"adjcore.loadout.3=key.keyboard.f3:NONE",
	"adjcore.hide_gui=key.keyboard.f8:NONE",
	"key.ftbquests.quests=key.keyboard.l:NONE",
	"ping-wheel.key.ping-location=key.keyboard.g:NONE",
	"ping-wheel.key.name-labels=key.keyboard.left.alt:NONE",
	"create.keyinfo.toolmenu=key.keyboard.left.alt:NONE",
	"create.keyinfo.toolbelt=key.keyboard.left.alt:NONE",
	"key.special_ability=key.keyboard.g:NONE",
	"key.jade.config=key.keyboard.keypad.0:NONE",
	"key.jade.show_overlay=key.keyboard.keypad.1:NONE",
	"key.jade.toggle_liquid=key.keyboard.keypad.2:NONE",
	"key.jade.show_recipes=key.keyboard.keypad.3:NONE",
	"key.jade.show_uses=key.keyboard.keypad.4:NONE",
	"key.jade.narrate=key.keyboard.keypad.5:NONE",
	"key.jade.show_details=key.keyboard.left.shift:NONE",
	"quark.keybind.back=key.mouse.4:NONE",
	"quark.keybind.camera_mode=key.keyboard.f12:NONE",
	"quark.keybind.change_hotbar=key.keyboard.unknown:NONE",
	"quark.keybind.lock_rotation=key.keyboard.k:NONE",
	"quark.keybind.variant_selector=key.keyboard.r:NONE",
	"supplementaries.keybind.quiver=key.keyboard.v:NONE",
	"key.presencefootsteps.settings=key.keyboard.f10:NONE",
]
